import { defineTool, planned, PHASE } from './define';

export const developerTools = [
  defineTool({
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate and minify JSON, with the exact position of syntax errors.',
    category: 'developer',
    icon: 'Braces',
    status: 'available',
    inputTypes: ['application/json', '.json'],
    intents: ['edit', 'analyze'],
    keywords: ['json', 'format', 'beautify', 'pretty print', 'validate', 'lint', 'minify'],
    aliases: ['json validator', 'json minifier', 'json beautifier', 'json viewer'],
    actionLabel: 'Format JSON',
    related: ['json-to-csv', 'csv-to-json', 'base64-text'],
    popular: true,
  }),
  defineTool({
    id: 'base64-text',
    name: 'Base64 Encoder / Decoder',
    description: 'Encode text to Base64 or decode it back. UTF-8 safe, including Hindi.',
    category: 'developer',
    icon: 'Binary',
    status: 'available',
    intents: ['convert'],
    keywords: ['base64', 'encode', 'decode', 'btoa', 'atob', 'url-safe'],
    limitations: ['Base64 is an encoding, not encryption. Anyone can decode it.'],
    related: ['url-encoder', 'image-to-base64', 'hash-generator'],
  }),
  defineTool({
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    description: 'Percent-encode or decode text for use in URLs.',
    category: 'developer',
    icon: 'Link',
    status: 'available',
    intents: ['convert'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri', 'escape'],
    related: ['url-parser', 'base64-text', 'html-entities'],
  }),
  defineTool({
    id: 'html-entities',
    name: 'HTML Entity Encoder / Decoder',
    description: 'Escape characters as HTML entities, or decode entities back to text.',
    category: 'developer',
    icon: 'Code',
    status: 'available',
    intents: ['convert'],
    keywords: ['html', 'entities', 'escape', 'unescape', 'encode', 'decode', '&amp;'],
    related: ['url-encoder', 'base64-text'],
  }),
  defineTool({
    id: 'url-parser',
    name: 'URL & Query String Parser',
    description: 'Break a URL into its parts and edit query parameters. Includes a UTM builder.',
    category: 'developer',
    icon: 'Globe',
    status: 'available',
    intents: ['analyze', 'create'],
    keywords: ['url', 'parse', 'query string', 'parameters', 'utm', 'builder', 'campaign'],
    aliases: ['query-string parser', 'query-string builder', 'utm builder'],
    related: ['url-encoder'],
  }),
  defineTool({
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode the header and payload of a JSON Web Token and show its expiry.',
    category: 'developer',
    icon: 'KeyRound',
    status: 'available',
    intents: ['analyze'],
    keywords: ['jwt', 'token', 'decode', 'json web token', 'claims', 'bearer'],
    limitations: ['Decoding does not verify the signature. Never trust a token just because it decodes.'],
    related: ['base64-text', 'json-formatter'],
  }),
  defineTool({
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test JavaScript regular expressions with live match highlighting and groups.',
    category: 'developer',
    icon: 'Regex',
    status: 'available',
    intents: ['analyze'],
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test'],
    limitations: ['Uses the JavaScript regex engine; syntax differs slightly from PCRE and Python.'],
    related: ['find-replace'],
  }),
  defineTool({
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colours between HEX, RGB, HSL and check contrast ratio.',
    category: 'developer',
    icon: 'Palette',
    status: 'available',
    intents: ['convert'],
    keywords: ['color', 'colour', 'hex', 'rgb', 'hsl', 'contrast', 'wcag', 'picker'],
    related: ['css-gradient'],
  }),
  planned({ id: 'yaml-formatter', name: 'YAML Formatter', description: 'Format YAML and convert JSON ↔ YAML.', category: 'developer', icon: 'FileCode', inputTypes: ['.yaml', '.yml'], keywords: ['yaml', 'yml', 'json to yaml'], reason: PHASE.data }),
  planned({ id: 'xml-formatter', name: 'XML Formatter', description: 'Format and validate XML.', category: 'developer', icon: 'FileCode', inputTypes: ['application/xml', '.xml'], keywords: ['xml', 'format'], reason: PHASE.data }),
  planned({ id: 'code-formatter', name: 'Code Formatter', description: 'Format HTML, CSS, JavaScript and SQL.', category: 'developer', icon: 'FileCode', keywords: ['html', 'css', 'javascript', 'sql', 'beautify', 'minify', 'formatter'], reason: PHASE.data }),
  planned({ id: 'css-gradient', name: 'CSS Gradient Generator', description: 'Build CSS gradients and shadows visually.', category: 'generators', icon: 'Blend', keywords: ['gradient', 'css', 'shadow', 'box-shadow'], reason: PHASE.productivity }),
];
