import { defineTool } from './define';

export const developerTools = [
  defineTool({
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate and minify JSON, with the exact position of syntax errors.',
    category: 'developer',
    icon: 'Braces',
    status: 'available',
    inputTypes: ['application/json', '.json'],
    intents: ['edit', 'analyze'],
    keywords: ['json', 'format', 'beautify', 'pretty print', 'validate', 'lint', 'minify'],
    aliases: ['json validator', 'json minifier', 'json beautifier', 'json viewer'],
    actionLabel: 'Format JSON',
    related: ['json-to-csv', 'csv-to-json', 'base64-text'],
    popular: true,
  }),
  defineTool({
    id: 'base64-text',
    name: 'Base64 Encoder / Decoder',
    description: 'Encode text to Base64 or decode it back. UTF-8 safe, including Hindi.',
    category: 'developer',
    icon: 'Binary',
    status: 'available',
    intents: ['convert'],
    keywords: ['base64', 'encode', 'decode', 'btoa', 'atob', 'url-safe'],
    limitations: ['Base64 is an encoding, not encryption. Anyone can decode it.'],
    related: ['url-encoder', 'image-to-base64', 'hash-generator'],
  }),
  defineTool({
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    description: 'Percent-encode or decode text for use in URLs.',
    category: 'developer',
    icon: 'Link',
    status: 'available',
    intents: ['convert'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri', 'escape'],
    related: ['url-parser', 'base64-text', 'html-entities'],
  }),
  defineTool({
    id: 'html-entities',
    name: 'HTML Entity Encoder / Decoder',
    description: 'Escape characters as HTML entities, or decode entities back to text.',
    category: 'developer',
    icon: 'Code',
    status: 'available',
    intents: ['convert'],
    keywords: ['html', 'entities', 'escape', 'unescape', 'encode', 'decode', '&amp;'],
    related: ['url-encoder', 'base64-text'],
  }),
  defineTool({
    id: 'url-parser',
    name: 'URL & Query String Parser',
    description: 'Break a URL into its parts and edit query parameters. Includes a UTM builder.',
    category: 'developer',
    icon: 'Globe',
    status: 'available',
    intents: ['analyze', 'create'],
    keywords: ['url', 'parse', 'query string', 'parameters', 'utm', 'builder', 'campaign'],
    aliases: ['query-string parser', 'query-string builder', 'utm builder'],
    related: ['url-encoder'],
  }),
  defineTool({
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode the header and payload of a JSON Web Token and show its expiry.',
    category: 'developer',
    icon: 'KeyRound',
    status: 'available',
    intents: ['analyze'],
    keywords: ['jwt', 'token', 'decode', 'json web token', 'claims', 'bearer'],
    limitations: ['Decoding does not verify the signature. Never trust a token just because it decodes.'],
    related: ['base64-text', 'json-formatter'],
  }),
  defineTool({
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test JavaScript regular expressions with live match highlighting and groups.',
    category: 'developer',
    icon: 'Regex',
    status: 'available',
    intents: ['analyze'],
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test'],
    limitations: ['Uses the JavaScript regex engine; syntax differs slightly from PCRE and Python.'],
    related: ['find-replace'],
  }),
  defineTool({
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colours between HEX, RGB, HSL and check contrast ratio.',
    category: 'developer',
    icon: 'Palette',
    status: 'available',
    intents: ['convert'],
    keywords: ['color', 'colour', 'hex', 'rgb', 'hsl', 'contrast', 'wcag', 'picker'],
    related: ['css-gradient'],
  }),
  defineTool({
    id: 'yaml-formatter',
    name: 'YAML Formatter & Converter',
    description: 'Validate and format YAML, and convert between YAML and JSON.',
    category: 'developer',
    icon: 'FileCode',
    status: 'available',
    inputTypes: ['.yaml', '.yml', 'application/yaml'],
    outputTypes: ['application/yaml', 'application/json'],
    intents: ['convert', 'edit'],
    keywords: ['yaml', 'yml', 'json to yaml', 'yaml to json', 'validate', 'format', 'kubernetes', 'docker compose'],
    aliases: ['json to yaml', 'yaml to json', 'yaml validator'],
    actionLabel: 'Format YAML',
    limitations: ['Comments are not preserved when re-formatting or converting.'],
    related: ['json-formatter', 'xml-formatter', 'code-formatter'],
  }),
  defineTool({
    id: 'xml-formatter',
    name: 'XML Formatter & Validator',
    description: 'Check XML is well-formed, then pretty-print or minify it.',
    category: 'developer',
    icon: 'FileCode',
    status: 'available',
    inputTypes: ['application/xml', '.xml', '.svg', '.xsd', '.rss', '.plist'],
    outputTypes: ['application/xml'],
    intents: ['edit', 'analyze'],
    keywords: ['xml', 'format', 'beautify', 'validate', 'minify', 'pretty print', 'sitemap', 'rss'],
    aliases: ['xml validator', 'xml beautifier', 'xml minifier'],
    actionLabel: 'Format XML',
    limitations: ['Checks well-formedness only, not schema (XSD/DTD) validity.'],
    related: ['json-formatter', 'yaml-formatter', 'code-formatter'],
  }),
  defineTool({
    id: 'code-formatter',
    name: 'Code Formatter',
    description: 'Beautify HTML, CSS, SCSS, JavaScript, TypeScript, JSON, Markdown, YAML, GraphQL and SQL.',
    category: 'developer',
    icon: 'FileCode',
    status: 'available',
    inputTypes: ['.html', '.css', '.scss', '.less', '.js', '.jsx', '.ts', '.tsx', '.sql', '.graphql'],
    intents: ['edit'],
    keywords: ['html', 'css', 'javascript', 'typescript', 'sql', 'beautify', 'formatter', 'prettier', 'pretty print', 'indent'],
    aliases: ['html formatter', 'css formatter', 'javascript formatter', 'sql formatter', 'code beautifier'],
    actionLabel: 'Format code',
    limitations: ['Code must be syntactically valid to be formatted.', 'Minification is not offered.'],
    related: ['json-formatter', 'xml-formatter', 'markdown-editor'],
  }),
  defineTool({
    id: 'css-gradient',
    name: 'CSS Gradient Generator',
    description: 'Build linear, radial and conic CSS gradients with a live preview.',
    category: 'generators',
    icon: 'Blend',
    status: 'available',
    intents: ['create'],
    keywords: ['gradient', 'css', 'background', 'linear-gradient', 'radial', 'conic'],
    related: ['css-shadow', 'color-converter'],
  }),
  defineTool({
    id: 'css-shadow',
    name: 'CSS Box Shadow Generator',
    description: 'Design layered box shadows visually and copy the CSS.',
    category: 'generators',
    icon: 'Blend',
    status: 'available',
    intents: ['create'],
    keywords: ['box-shadow', 'shadow', 'css', 'elevation', 'neumorphism'],
    related: ['css-gradient', 'color-converter'],
  }),
  defineTool({
    id: 'http-headers',
    name: 'HTTP Header Parser',
    description: 'Tidy raw HTTP headers, export them as JSON and check common security headers.',
    category: 'developer',
    icon: 'Globe',
    status: 'available',
    intents: ['analyze'],
    keywords: ['http', 'headers', 'response', 'request', 'security headers', 'csp', 'hsts', 'curl'],
    aliases: ['http header formatter'],
    related: ['url-parser', 'user-agent', 'jwt-decoder'],
  }),
  defineTool({
    id: 'user-agent',
    name: 'User-Agent Info',
    description: 'See your browser’s user agent and client hints, or parse any user-agent string.',
    category: 'developer',
    icon: 'Info',
    status: 'beta',
    intents: ['analyze'],
    keywords: ['user agent', 'ua', 'browser', 'what is my browser', 'client hints'],
    limitations: ['Parsing is heuristic; user-agent strings can be faked and are partly frozen in modern browsers.'],
    related: ['http-headers', 'url-parser'],
  }),
];
