import { defineTool, planned, IMAGE_IN, RASTER_OUT, PHASE } from './define';

const imageHelp = {
  problems: [
    'HEIC/HEIF photos from iPhones are not decoded by most browsers — export them as JPEG first.',
    'Animated GIF and WebP files are processed as a single still frame.',
  ],
  fileSize: 'Images up to roughly 40 megapixels work on most devices. Larger images may exhaust browser memory, especially on phones.',
  browsers: 'WebP export is supported in Chrome, Edge, Firefox and Opera. Older Safari versions may fall back to PNG.',
  troubleshooting: ['Reload the page and try again.', 'Try a smaller image.', 'Try a different output format.'],
};

const rasterLimitations = [
  'Animated images become a single frame.',
  'Colour profiles (ICC) and EXIF metadata are not preserved in the output.',
];

const conv = (id: string, name: string, from: string[], to: string, fromLabel: string, toLabel: string) =>
  defineTool({
    id,
    name,
    description: `Convert ${fromLabel} images to ${toLabel} locally in your browser.`,
    category: 'image',
    icon: 'Repeat',
    status: 'available',
    batch: true,
    inputTypes: from,
    outputTypes: [to],
    intents: ['convert'],
    keywords: [fromLabel.toLowerCase(), toLabel.toLowerCase(), 'convert', 'image', 'format'],
    actionLabel: `Convert to ${toLabel}`,
    limitations: rasterLimitations,
    related: ['image-converter', 'image-compressor', 'image-resizer'],
    help: imageHelp,
    requires: ['workers'],
  });

export const imageTools = [
  defineTool({
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by pixels or percentage, one at a time or in bulk.',
    category: 'image',
    icon: 'Scaling',
    status: 'available',
    batch: true,
    inputTypes: IMAGE_IN,
    outputTypes: RASTER_OUT,
    intents: ['edit'],
    keywords: ['resize', 'scale', 'dimensions', 'width', 'height', 'shrink', 'enlarge', 'bulk'],
    aliases: ['bulk image resizer', 'photo resizer'],
    actionLabel: 'Resize',
    limitations: rasterLimitations,
    related: ['image-compressor', 'image-converter', 'image-cropper', 'image-to-pdf'],
    help: imageHelp,
    popular: true,
  }),
  defineTool({
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between JPEG, PNG and WebP, including bulk conversion.',
    category: 'image',
    icon: 'Repeat',
    status: 'available',
    batch: true,
    inputTypes: [...IMAGE_IN, 'image/svg+xml'],
    outputTypes: RASTER_OUT,
    intents: ['convert'],
    keywords: ['convert', 'format', 'jpg', 'jpeg', 'png', 'webp', 'bulk'],
    aliases: ['bulk image converter', 'photo converter'],
    actionLabel: 'Convert',
    limitations: rasterLimitations,
    related: ['image-compressor', 'image-resizer', 'image-to-pdf'],
    help: imageHelp,
    popular: true,
  }),
  defineTool({
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size by re-encoding with adjustable quality.',
    category: 'image',
    icon: 'Minimize2',
    status: 'available',
    batch: true,
    inputTypes: IMAGE_IN,
    outputTypes: ['image/jpeg', 'image/webp'],
    intents: ['compress'],
    keywords: ['compress', 'reduce', 'optimize', 'smaller', 'size', 'quality', 'bulk'],
    aliases: ['bulk image compressor', 'photo compressor', 'shrink image'],
    actionLabel: 'Compress',
    limitations: [
      ...rasterLimitations,
      'PNG input is re-encoded as JPEG or WebP; transparency is kept only with WebP.',
      'Already-optimised images may not get smaller. The tool tells you when the result is larger.',
    ],
    related: ['image-resizer', 'image-converter', 'pdf-compressor'],
    help: imageHelp,
    popular: true,
  }),
  defineTool({
    id: 'image-rotator',
    name: 'Rotate Image',
    description: 'Rotate images by 90°, 180° or 270°.',
    category: 'image',
    icon: 'RotateCw',
    status: 'available',
    batch: true,
    inputTypes: IMAGE_IN,
    outputTypes: RASTER_OUT,
    intents: ['edit'],
    keywords: ['rotate', 'turn', 'orientation', '90'],
    actionLabel: 'Rotate',
    limitations: rasterLimitations,
    related: ['image-flipper', 'image-resizer', 'image-cropper'],
    help: imageHelp,
  }),
  defineTool({
    id: 'image-flipper',
    name: 'Flip Image',
    description: 'Mirror images horizontally or vertically.',
    category: 'image',
    icon: 'FlipHorizontal2',
    status: 'available',
    batch: true,
    inputTypes: IMAGE_IN,
    outputTypes: RASTER_OUT,
    intents: ['edit'],
    keywords: ['flip', 'mirror', 'horizontal', 'vertical'],
    actionLabel: 'Flip',
    limitations: rasterLimitations,
    related: ['image-rotator', 'image-resizer'],
    help: imageHelp,
  }),
  conv('jpg-to-png', 'JPG to PNG', ['image/jpeg'], 'image/png', 'JPG', 'PNG'),
  conv('png-to-jpg', 'PNG to JPG', ['image/png'], 'image/jpeg', 'PNG', 'JPG'),
  conv('jpg-to-webp', 'JPG to WebP', ['image/jpeg'], 'image/webp', 'JPG', 'WebP'),
  conv('png-to-webp', 'PNG to WebP', ['image/png'], 'image/webp', 'PNG', 'WebP'),
  conv('webp-to-jpg', 'WebP to JPG', ['image/webp'], 'image/jpeg', 'WebP', 'JPG'),
  conv('webp-to-png', 'WebP to PNG', ['image/webp'], 'image/png', 'WebP', 'PNG'),
  defineTool({
    ...conv('svg-to-png', 'SVG to PNG', ['image/svg+xml'], 'image/png', 'SVG', 'PNG'),
    status: 'beta',
    limitations: [
      'SVGs that reference external images or web fonts render without them.',
      'SVGs without width/height or a viewBox are rendered at 1024 px.',
    ],
  }),
  defineTool({
    id: 'image-info',
    name: 'Image Information',
    description: 'View dimensions, format, file size, aspect ratio and detected type of an image.',
    category: 'image',
    icon: 'Info',
    status: 'available',
    batch: true,
    inputTypes: [...IMAGE_IN, 'image/svg+xml'],
    intents: ['analyze'],
    keywords: ['info', 'metadata', 'dimensions', 'resolution', 'details', 'properties'],
    aliases: ['image metadata viewer', 'image dimension'],
    actionLabel: 'Inspect',
    limitations: ['EXIF/camera metadata reading is coming in a later update.'],
    related: ['file-info', 'image-resizer'],
  }),
  defineTool({
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Encode an image as a Base64 data URI for embedding in HTML or CSS.',
    category: 'image',
    icon: 'Binary',
    status: 'available',
    inputTypes: [...IMAGE_IN, 'image/svg+xml'],
    intents: ['convert'],
    keywords: ['base64', 'data uri', 'encode', 'embed', 'inline'],
    actionLabel: 'To Base64',
    limitations: ['Base64 output is about 33% larger than the original file.'],
    related: ['base64-to-image', 'base64-text'],
  }),
  defineTool({
    id: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Decode a Base64 string or data URI back into a downloadable image.',
    category: 'image',
    icon: 'FileImage',
    status: 'available',
    outputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml'],
    intents: ['convert'],
    keywords: ['base64', 'data uri', 'decode', 'image'],
    related: ['image-to-base64', 'base64-text'],
  }),
  defineTool({
    id: 'image-cropper',
    name: 'Crop Image',
    description: 'Crop images with a draggable box, aspect-ratio presets and exact pixel values.',
    category: 'image',
    icon: 'Crop',
    status: 'available',
    inputTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp', 'image/avif'],
    outputTypes: RASTER_OUT,
    intents: ['edit'],
    keywords: ['crop', 'trim', 'cut', 'aspect ratio', 'square', 'instagram', '16:9'],
    actionLabel: 'Crop',
    limitations: rasterLimitations,
    related: ['image-resizer', 'image-rotator', 'favicon-generator'],
    help: imageHelp,
  }),
  defineTool({
    id: 'image-watermark',
    name: 'Image Watermark',
    description: 'Add a text or logo watermark to one or many images. Text can be in any language, including Hindi.',
    category: 'image',
    icon: 'Stamp',
    status: 'available',
    batch: true,
    inputTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    outputTypes: RASTER_OUT,
    intents: ['edit'],
    keywords: ['watermark', 'stamp', 'logo', 'copyright', 'protect', 'bulk'],
    actionLabel: 'Watermark',
    limitations: [...rasterLimitations, 'Text uses fonts installed on your device, so it can look slightly different across devices.'],
    related: ['pdf-watermark', 'image-resizer', 'image-compressor'],
    help: imageHelp,
  }),
  defineTool({
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create favicon.ico, PNG icons, the Apple touch icon and a web manifest from one image.',
    category: 'image',
    icon: 'AppWindow',
    status: 'available',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'],
    outputTypes: ['image/x-icon', 'image/png', 'application/zip'],
    intents: ['create', 'convert'],
    keywords: ['favicon', 'ico', 'icon', 'website', 'apple touch icon', 'manifest', 'pwa', 'png to ico'],
    aliases: ['ico generator', 'ico converter'],
    actionLabel: 'Make favicon',
    limitations: ['Start from a square image of at least 512 × 512 px for the sharpest results.'],
    related: ['image-cropper', 'image-resizer', 'image-converter'],
  }),
  defineTool({
    id: 'photopea',
    name: 'Image Editor (Photopea)',
    description: 'Advanced layer-based image editing using Photopea, an external web application.',
    category: 'image',
    icon: 'ExternalLink',
    status: 'available',
    processing: 'external',
    offline: 'no',
    externalService: { name: 'Photopea', url: 'https://www.photopea.com' },
    inputTypes: [...IMAGE_IN, 'image/svg+xml', 'image/vnd.adobe.photoshop', '.psd', '.xcf', '.sketch'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/vnd.adobe.photoshop'],
    intents: ['edit'],
    keywords: ['editor', 'photoshop', 'layers', 'photopea', 'edit', 'psd', 'image editor', 'retouch', 'full screen'],
    aliases: ['photo editor', 'psd editor', 'online photoshop'],
    actionLabel: 'Edit in Photopea',
    limitations: [
      'Photopea is a third-party service from photopea.com. It needs an internet connection and shows Photopea’s ads; their privacy policy applies.',
      'Files you open are handed to the Photopea frame in your browser. Photopea states it edits files on your device, but this app cannot verify that.',
      'Works best on a desktop or tablet.',
    ],
    related: ['image-cropper', 'image-resizer', 'image-watermark'],
    popular: true,
  }),
  planned({ id: 'background-remover', name: 'Background Remover', description: 'Remove image backgrounds.', category: 'image', icon: 'Eraser', inputTypes: IMAGE_IN, keywords: ['background', 'remove', 'cutout', 'transparent'], reason: PHASE.ai }),
  planned({ id: 'heic-converter', name: 'HEIC Converter', description: 'Convert iPhone HEIC photos.', category: 'image', icon: 'Repeat', inputTypes: ['image/heic', 'image/heif'], keywords: ['heic', 'heif', 'iphone'], reason: 'Browsers do not decode HEIC natively; a reliable WebAssembly decoder is still being evaluated.' }),
];
