import { defineTool } from './define';

const CSV = ['text/csv', '.csv', '.tsv', 'text/tab-separated-values'];

export const securityTools = [
  defineTool({
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong random passwords using your browser’s cryptographic random source.',
    category: 'security',
    icon: 'KeySquare',
    status: 'available',
    intents: ['create'],
    keywords: ['password', 'generate', 'random', 'strong', 'secure'],
    requires: ['webCrypto'],
    related: ['uuid-generator', 'random-token', 'hash-generator'],
    popular: true,
  }),
  defineTool({
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate version 4 UUIDs, one or many at a time.',
    category: 'security',
    icon: 'Fingerprint',
    status: 'available',
    intents: ['create'],
    keywords: ['uuid', 'guid', 'unique id', 'v4', 'identifier'],
    requires: ['webCrypto'],
    related: ['random-token', 'password-generator'],
  }),
  defineTool({
    id: 'random-token',
    name: 'Random Token Generator',
    description: 'Generate random tokens in hex, Base64 or Base64URL.',
    category: 'security',
    icon: 'Dices',
    status: 'available',
    intents: ['create'],
    keywords: ['token', 'random', 'secret', 'api key', 'hex', 'nonce'],
    requires: ['webCrypto'],
    related: ['password-generator', 'uuid-generator'],
  }),
  defineTool({
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Compute SHA-1, SHA-256, SHA-384 and SHA-512 hashes of text or files.',
    category: 'security',
    icon: 'Hash',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    intents: ['analyze'],
    keywords: ['hash', 'sha256', 'sha-256', 'sha512', 'sha1', 'checksum', 'digest', 'verify'],
    aliases: ['sha-256', 'sha-512', 'file hash', 'checksum'],
    actionLabel: 'Hash',
    limitations: [
      'Hashing is one-way; it is not encryption and cannot be reversed.',
      'MD5 is not offered because browsers do not provide it and it is unsafe for security use.',
      'Files are read fully into memory before hashing.',
    ],
    requires: ['webCrypto'],
    related: ['file-info', 'password-generator'],
  }),
  defineTool({
    id: 'file-encrypt',
    name: 'File Encryption',
    description: 'Lock any file with a password (AES-256) and unlock it later. Protects your own documents — nothing is uploaded.',
    category: 'security',
    icon: 'Lock',
    status: 'available',
    inputTypes: ['*/*'],
    outputTypes: ['application/octet-stream'],
    intents: ['edit'],
    keywords: ['encrypt file', 'password protect file', 'aes', 'decrypt', 'lock file', 'encrypt pdf', 'secure file', 'file password'],
    aliases: ['encrypt file online', 'password protect a file', 'decrypt file'],
    actionLabel: 'Encrypt / decrypt',
    requires: ['webCrypto'],
    limitations: ['If you forget the password the file cannot be recovered by anyone.', 'Encrypted files use a .dsenc container that this tool (or any AES-256-GCM tool with the format) can open.'],
    related: ['passphrase-generator', 'password-strength', 'hash-generator'],
    popular: true,
  }),
  defineTool({
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'See how strong a password is and roughly how long it would take to crack — checked entirely in your browser, never sent anywhere.',
    category: 'security',
    icon: 'ShieldCheck',
    status: 'available',
    intents: ['analyze'],
    keywords: ['password strength', 'password checker', 'how strong is my password', 'password tester', 'crack time', 'password entropy'],
    aliases: ['password strength meter', 'test password strength'],
    related: ['passphrase-generator', 'password-generator', 'file-encrypt'],
  }),
  defineTool({
    id: 'totp-generator',
    name: '2FA / TOTP Code Generator',
    description: 'Generate time-based two-factor (2FA) codes from a secret key or QR code, like Google Authenticator — in your browser.',
    category: 'security',
    icon: 'Clock',
    status: 'available',
    intents: ['create'],
    keywords: ['2fa', 'totp', 'authenticator', 'one time password', 'otp', 'google authenticator', 'two factor', 'authenticator code'],
    aliases: ['totp generator', '2fa code generator', 'authenticator online'],
    requires: ['webCrypto'],
    limitations: ['The secret is kept only in this tab and forgotten when you close it; nothing is saved or synced.', 'For best security keep 2FA on a different device from the one you log in with.'],
    related: ['qr-reader', 'passphrase-generator'],
  }),
  defineTool({
    id: 'passphrase-generator',
    name: 'Passphrase Generator',
    description: 'Strong, memorable passphrases like “velvet-orbit-canyon-sprout-mango-tidal” from the EFF word list, with an honest strength estimate.',
    category: 'security',
    icon: 'KeySquare',
    status: 'available',
    intents: ['create'],
    keywords: ['passphrase', 'diceware', 'memorable password', 'strong password', 'random words', 'eff word list', 'xkcd password'],
    aliases: ['diceware generator', 'memorable password generator'],
    requires: ['webCrypto'],
    related: ['password-generator', 'random-token', 'hash-generator'],
  }),
  defineTool({
    id: 'qr-reader',
    name: 'QR Code Reader',
    description: 'Scan a QR code from an image or your camera and see exactly where it leads before you open it.',
    category: 'security',
    icon: 'ScanLine',
    status: 'available',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/bmp'],
    intents: ['analyze'],
    keywords: ['qr', 'qr code', 'scan', 'reader', 'scanner', 'decode', 'camera', 'upi', 'wifi', 'safe link', 'barcode'],
    aliases: ['qr scanner', 'scan qr code online', 'qr code decoder'],
    actionLabel: 'Scan QR',
    limitations: ['Camera scanning needs camera permission; video frames are processed in the page and never recorded or uploaded.', 'Very small, blurred or heavily stylised codes may not be readable.'],
    related: ['qr-generator', 'barcode-generator'],
  }),
];

export const dataTools = [
  defineTool({
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV or TSV to JSON. Detects the delimiter and handles quoted fields.',
    category: 'spreadsheets',
    icon: 'FileJson',
    status: 'available',
    inputTypes: CSV,
    outputTypes: ['application/json'],
    intents: ['convert'],
    keywords: ['csv', 'tsv', 'json', 'convert', 'spreadsheet', 'table'],
    aliases: ['tsv to json'],
    actionLabel: 'To JSON',
    limitations: ['Excel files (.xlsx) must be saved as CSV first.'],
    related: ['json-to-csv', 'json-formatter'],
    popular: true,
  }),
  defineTool({
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert a JSON array of objects to CSV, ready for Excel or Google Sheets.',
    category: 'spreadsheets',
    icon: 'Table',
    status: 'available',
    inputTypes: ['application/json', '.json'],
    outputTypes: ['text/csv'],
    intents: ['convert'],
    keywords: ['json', 'csv', 'convert', 'excel', 'spreadsheet', 'export'],
    actionLabel: 'To CSV',
    limitations: ['Nested objects are written as JSON text inside the cell.'],
    related: ['csv-to-json', 'json-formatter'],
  }),
  defineTool({
    id: 'csv-viewer',
    name: 'CSV Viewer & Editor',
    description: 'View, sort, filter and edit CSV/TSV files. Clean data, remove duplicates, split or merge columns.',
    category: 'spreadsheets',
    icon: 'Sheet',
    status: 'available',
    inputTypes: ['text/csv', '.csv', '.tsv', 'text/tab-separated-values', '.txt'],
    outputTypes: ['text/csv', 'application/json'],
    intents: ['edit', 'analyze'],
    keywords: ['csv', 'viewer', 'editor', 'grid', 'table', 'clean', 'duplicate rows', 'columns', 'split column', 'merge columns', 'tsv', 'sort', 'filter'],
    aliases: ['csv cleaner', 'duplicate row remover', 'column splitter', 'column merger', 'tsv to csv', 'data formatter'],
    actionLabel: 'View / edit',
    limitations: ['The whole file is loaded into memory; files of a few hundred MB may be slow on phones.'],
    related: ['csv-to-json', 'spreadsheet-viewer', 'json-to-csv'],
  }),
  defineTool({
    id: 'spreadsheet-viewer',
    name: 'Spreadsheet Viewer',
    description: 'Open Excel and OpenDocument spreadsheets, browse sheets and export them to CSV or JSON.',
    category: 'spreadsheets',
    icon: 'Sheet',
    status: 'available',
    inputTypes: ['.xlsx', '.xlsm', '.xls', '.xlsb', '.ods', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'application/vnd.oasis.opendocument.spreadsheet'],
    outputTypes: ['text/csv', 'application/json'],
    intents: ['convert', 'analyze'],
    keywords: ['excel', 'xlsx', 'xls', 'ods', 'spreadsheet', 'viewer', 'excel to csv', 'excel to json', 'metadata', 'sheets'],
    aliases: ['excel viewer', 'xlsx to csv', 'excel to csv', 'spreadsheet metadata viewer'],
    actionLabel: 'Open spreadsheet',
    limitations: ['Charts, images, formatting and macros are not shown; macros never run.', 'Password-protected workbooks are not supported.'],
    related: ['csv-viewer', 'csv-to-json', 'excel-to-pdf'],
  }),
  defineTool({
    id: 'presentation-info',
    name: 'PowerPoint Inspector',
    description: 'Open a .pptx to see every slide’s title, text and speaker notes, extract all images and media, and check hidden slides and author details.',
    category: 'presentations',
    icon: 'Presentation',
    status: 'available',
    inputTypes: ['.pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    outputTypes: ['text/plain'],
    intents: ['analyze', 'convert'],
    keywords: ['pptx', 'powerpoint', 'slides', 'extract images from pptx', 'pptx to text', 'speaker notes', 'presentation metadata', 'hidden slides'],
    aliases: ['pptx to text', 'extract images from powerpoint', 'powerpoint viewer'],
    actionLabel: 'Inspect slides',
    limitations: ['Shows text, notes and media — slides are not rendered visually.', 'Old .ppt files must be saved as .pptx first.'],
    related: ['pdf-to-text', 'zip-extractor', 'image-compressor'],
  }),
];

export const calculatorTools = [
  defineTool({
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Percent of a number, percentage change, discounts and profit/loss — with formulas shown.',
    category: 'calculators',
    icon: 'Percent',
    status: 'available',
    intents: ['analyze'],
    keywords: ['percent', 'percentage', 'discount', 'change', 'increase', 'decrease', 'profit', 'loss', 'margin'],
    aliases: ['discount calculator', 'profit loss calculator'],
    related: ['gst-calculator', 'emi-calculator'],
  }),
  defineTool({
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Add or remove GST at Indian slab rates, with CGST/SGST split.',
    category: 'calculators',
    icon: 'Receipt',
    status: 'available',
    intents: ['analyze'],
    keywords: ['gst', 'tax', 'cgst', 'sgst', 'igst', 'india', 'inclusive', 'exclusive'],
    limitations: ['Rates are the common slabs; check current government notifications for your item.'],
    related: ['percentage-calculator', 'emi-calculator'],
  }),
  defineTool({
    id: 'emi-calculator',
    name: 'EMI / Loan Calculator',
    description: 'Monthly instalment, total interest and amortisation schedule for a loan.',
    category: 'calculators',
    icon: 'Landmark',
    status: 'available',
    intents: ['analyze'],
    keywords: ['emi', 'loan', 'mortgage', 'home loan', 'interest', 'amortization', 'instalment'],
    aliases: ['loan calculator'],
    limitations: ['Assumes a fixed rate and monthly reducing balance. Lenders may round differently.'],
    related: ['interest-calculator', 'percentage-calculator'],
  }),
  defineTool({
    id: 'interest-calculator',
    name: 'Interest Calculator',
    description: 'Simple and compound interest with monthly deposits, effective annual rate and a year-by-year table.',
    category: 'calculators',
    icon: 'TrendingUp',
    status: 'available',
    intents: ['analyze'],
    keywords: ['simple interest', 'compound interest', 'fd', 'fixed deposit', 'rd', 'sip', 'savings', 'maturity', 'investment', 'ear', 'apy'],
    aliases: ['compound interest calculator', 'fd calculator', 'rd calculator'],
    limitations: ['Assumes a fixed rate for the whole period and deposits at the end of each month. Tax (TDS) is not deducted.'],
    related: ['emi-calculator', 'percentage-calculator'],
  }),
  defineTool({
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Trigonometry, logarithms, powers, roots, factorials and nCr — type an expression or use the keypad.',
    category: 'calculators',
    icon: 'Calculator',
    status: 'available',
    intents: ['analyze'],
    keywords: ['calculator', 'scientific', 'basic', 'sin', 'cos', 'tan', 'log', 'ln', 'power', 'square root', 'factorial', 'degrees', 'radians'],
    aliases: ['online calculator', 'basic calculator'],
    limitations: ['Uses standard double-precision numbers (about 15–16 significant digits).'],
    related: ['percentage-calculator', 'unit-converter'],
    popular: true,
  }),
  defineTool({
    id: 'date-calculator',
    name: 'Date & Age Calculator',
    description: 'Exact age, days between two dates (with working days), and adding or subtracting days, weeks, months or years.',
    category: 'calculators',
    icon: 'CalendarDays',
    status: 'available',
    intents: ['analyze'],
    keywords: ['age', 'date', 'days between', 'date difference', 'working days', 'business days', 'birthday', 'add days', 'time'],
    aliases: ['age calculator', 'days calculator', 'date difference calculator'],
    limitations: ['Working days count Monday to Friday; public holidays are not excluded.'],
    related: ['scientific-calculator', 'timer'],
  }),
  defineTool({
    id: 'time-calculator',
    name: 'Time Calculator',
    description: 'Add and subtract hours, minutes and seconds, total hours worked (with breaks and night shifts), add time to a clock, and convert decimal hours.',
    category: 'calculators',
    icon: 'Clock',
    status: 'available',
    intents: ['analyze'],
    keywords: ['time calculator', 'hours calculator', 'add time', 'subtract time', 'hours and minutes', 'timesheet', 'hours worked', 'decimal hours', 'time duration', 'shift calculator', 'overtime'],
    aliases: ['hours calculator', 'time duration calculator', 'timesheet calculator', 'decimal hours converter'],
    limitations: ['Hours worked count Monday to Sunday the same; overtime rules and public holidays are not applied.'],
    related: ['date-calculator', 'time-zone-converter', 'timer'],
    popular: true,
  }),
  defineTool({
    id: 'time-zone-converter',
    name: 'Time Zone Converter',
    description: 'Convert a date and time between IST and any city or time zone, with daylight saving applied automatically.',
    category: 'calculators',
    icon: 'Globe',
    status: 'available',
    intents: ['convert'],
    keywords: ['time zone converter', 'ist to est', 'ist to pst', 'ist to gmt', 'world clock', 'meeting time', 'utc', 'timezone', 'daylight saving'],
    aliases: ['ist converter', 'world time converter', 'meeting planner'],
    limitations: ['Uses your browser’s time-zone database, which is updated with the browser.'],
    related: ['time-calculator', 'date-calculator'],
  }),
  defineTool({
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Body mass index for adults in metric or imperial units, with WHO and Asian-Indian categories and a healthy weight range.',
    category: 'calculators',
    icon: 'Activity',
    status: 'available',
    intents: ['analyze'],
    keywords: ['bmi', 'body mass index', 'weight', 'height', 'obesity', 'overweight', 'healthy weight', 'asian bmi'],
    limitations: ['For adults (18+). BMI does not measure body fat directly and is not a diagnosis — ask a doctor about your health.'],
    related: ['unit-converter', 'date-calculator'],
  }),
  defineTool({
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Length, area, volume, weight, temperature, speed, time, data, pressure, energy, power, frequency and angle.',
    category: 'converters',
    icon: 'Ruler',
    status: 'available',
    intents: ['convert'],
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'metric', 'imperial', 'km', 'miles', 'kg', 'pounds', 'celsius', 'fahrenheit', 'bytes', 'mb', 'gb', 'pressure', 'bar', 'psi', 'energy', 'power', 'angle'],
    aliases: ['length converter', 'weight converter', 'temperature converter', 'data storage converter'],
    popular: true,
  }),
];

export const fileTools = [
  defineTool({
    id: 'metadata-editor',
    name: 'Metadata Editor',
    description: 'View, change and remove metadata in one place — photo EXIF (date taken, camera, GPS), PNG text, PDF properties, MP4/MOV video dates, MP3 song tags, and Office (.docx/.xlsx/.pptx) created/modified dates.',
    category: 'files',
    icon: 'FileSearch',
    status: 'available',
    inputTypes: ['image/jpeg', 'image/png', 'application/pdf', 'video/mp4', 'video/quicktime', 'audio/mpeg', '.jpg', '.jpeg', '.png', '.pdf', '.mp4', '.mov', '.m4v', '.mp3', '.docx', '.xlsx', '.pptx'],
    outputTypes: ['image/jpeg', 'image/png', 'application/pdf', 'video/mp4', 'audio/mpeg'],
    intents: ['edit', 'analyze'],
    keywords: ['metadata editor', 'edit exif', 'change photo date', 'change date taken', 'edit metadata', 'change exif date', 'edit pdf date', 'exif editor', 'change metadata date', 'change video date', 'edit mp3 tags', 'id3 editor', 'change created date', 'edit docx metadata'],
    aliases: ['exif editor', 'change date taken on photo', 'edit photo metadata', 'metadata changer', 'mp3 tag editor', 'change video media created date'],
    actionLabel: 'Edit metadata',
    limitations: ['Edits the metadata stored inside the file (EXIF date taken, PDF/video/Office created & modified dates, MP3 tags). The operating-system “date modified” cannot be changed from a browser.', 'Video and audio are not re-encoded — only their metadata fields change. Old .ppt/.doc/.xls (pre-2007) are not supported.'],
    related: ['image-metadata', 'pdf-metadata', 'image-info'],
    popular: true,
  }),
  defineTool({
    id: 'file-info',
    name: 'File Information',
    description: 'Detect the real file type from its contents, and view size, extension and SHA-256.',
    category: 'files',
    icon: 'FileSearch',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    intents: ['analyze'],
    keywords: ['file', 'info', 'mime', 'type', 'extension', 'size', 'detect', 'magic bytes', 'duplicate'],
    aliases: ['mime type detector', 'file size analyzer', 'extension detector', 'duplicate file finder'],
    actionLabel: 'File info',
    limitations: ['Duplicate detection compares SHA-256 hashes of the files you add.'],
    related: ['hash-generator', 'zip-creator'],
  }),
  defineTool({
    id: 'zip-creator',
    name: 'Create ZIP',
    description: 'Bundle files into a ZIP archive.',
    category: 'files',
    icon: 'FileArchive',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    outputTypes: ['application/zip'],
    intents: ['compress'],
    keywords: ['zip', 'archive', 'compress', 'bundle'],
    actionLabel: 'Add to ZIP',
    limitations: ['Password-protected ZIPs are not supported.'],
    related: ['zip-extractor', 'file-info'],
  }),
  defineTool({
    id: 'zip-extractor',
    name: 'Extract ZIP',
    description: 'Open a ZIP archive and download individual files.',
    category: 'files',
    icon: 'PackageOpen',
    status: 'available',
    inputTypes: ['application/zip', '.zip'],
    intents: ['convert'],
    keywords: ['unzip', 'extract', 'zip', 'archive', 'open'],
    actionLabel: 'Extract',
    limitations: ['Encrypted ZIP files and ZIP64 archives over ~2 GB are not supported.', 'The whole archive is loaded into memory.'],
    related: ['zip-creator', 'file-info'],
  }),
  defineTool({
    id: 'share-link',
    name: 'Share File via Link',
    description: 'Put a small file, photo or note inside a link and send it — the receiver opens it to view or edit. Nothing is uploaded; optional password.',
    category: 'files',
    icon: 'Link2',
    status: 'available',
    inputTypes: ['*/*'],
    intents: ['convert'],
    keywords: ['share file link', 'send file without upload', 'file to link', 'image to link', 'share photo link', 'share note', 'url', 'encrypted link', 'password'],
    aliases: ['file to url', 'share image as link', 'send photo via link'],
    actionLabel: 'Share as link',
    limitations: [
      'The file travels inside the link, so links grow with the file: best for notes, text, CSV and small or reduced photos (about 1 MB at most). Large photos, PDFs and videos are too big.',
      'Some chat apps cut very long links; open the link yourself once to check it arrived whole.',
      'Anyone who has the link can open the file unless you add a password.',
    ],
    related: ['qr-generator', 'image-compressor', 'notes'],
  }),
];
