import { defineTool, planned, PHASE } from './define';

const CSV = ['text/csv', '.csv', '.tsv', 'text/tab-separated-values'];

export const securityTools = [
  defineTool({
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong random passwords using your browser’s cryptographic random source.',
    category: 'security',
    icon: 'KeySquare',
    status: 'available',
    intents: ['create'],
    keywords: ['password', 'generate', 'random', 'strong', 'secure'],
    requires: ['webCrypto'],
    related: ['uuid-generator', 'random-token', 'hash-generator'],
    popular: true,
  }),
  defineTool({
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate version 4 UUIDs, one or many at a time.',
    category: 'security',
    icon: 'Fingerprint',
    status: 'available',
    intents: ['create'],
    keywords: ['uuid', 'guid', 'unique id', 'v4', 'identifier'],
    requires: ['webCrypto'],
    related: ['random-token', 'password-generator'],
  }),
  defineTool({
    id: 'random-token',
    name: 'Random Token Generator',
    description: 'Generate random tokens in hex, Base64 or Base64URL.',
    category: 'security',
    icon: 'Dices',
    status: 'available',
    intents: ['create'],
    keywords: ['token', 'random', 'secret', 'api key', 'hex', 'nonce'],
    requires: ['webCrypto'],
    related: ['password-generator', 'uuid-generator'],
  }),
  defineTool({
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Compute SHA-1, SHA-256, SHA-384 and SHA-512 hashes of text or files.',
    category: 'security',
    icon: 'Hash',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    intents: ['analyze'],
    keywords: ['hash', 'sha256', 'sha-256', 'sha512', 'sha1', 'checksum', 'digest', 'verify'],
    aliases: ['sha-256', 'sha-512', 'file hash', 'checksum'],
    actionLabel: 'Hash',
    limitations: [
      'Hashing is one-way; it is not encryption and cannot be reversed.',
      'MD5 is not offered because browsers do not provide it and it is unsafe for security use.',
      'Files are read fully into memory before hashing.',
    ],
    requires: ['webCrypto'],
    related: ['file-info', 'password-generator'],
  }),
  planned({ id: 'passphrase-generator', name: 'Passphrase Generator', description: 'Generate memorable multi-word passphrases.', category: 'security', icon: 'KeySquare', keywords: ['passphrase', 'diceware', 'words'], reason: 'Needs a curated word list bundled for offline use.' }),
  planned({ id: 'qr-generator', name: 'QR Code Generator', description: 'Create QR codes for text, links and Wi-Fi.', category: 'generators', icon: 'QrCode', intents: ['create'], keywords: ['qr', 'qr code', 'barcode'], reason: PHASE.productivity }),
  planned({ id: 'qr-reader', name: 'QR Code Reader', description: 'Read QR codes from an image or camera.', category: 'security', icon: 'ScanLine', inputTypes: ['image/png', 'image/jpeg'], keywords: ['qr', 'scan', 'read'], reason: PHASE.productivity }),
  planned({ id: 'barcode-generator', name: 'Barcode Generator', description: 'Create Code 128 and EAN barcodes.', category: 'generators', icon: 'Barcode', keywords: ['barcode', 'ean', 'code128'], reason: PHASE.productivity }),
];

export const dataTools = [
  defineTool({
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV or TSV to JSON. Detects the delimiter and handles quoted fields.',
    category: 'spreadsheets',
    icon: 'FileJson',
    status: 'available',
    inputTypes: CSV,
    outputTypes: ['application/json'],
    intents: ['convert'],
    keywords: ['csv', 'tsv', 'json', 'convert', 'spreadsheet', 'table'],
    aliases: ['tsv to json'],
    actionLabel: 'To JSON',
    limitations: ['Excel files (.xlsx) must be saved as CSV first.'],
    related: ['json-to-csv', 'json-formatter'],
    popular: true,
  }),
  defineTool({
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert a JSON array of objects to CSV, ready for Excel or Google Sheets.',
    category: 'spreadsheets',
    icon: 'Table',
    status: 'available',
    inputTypes: ['application/json', '.json'],
    outputTypes: ['text/csv'],
    intents: ['convert'],
    keywords: ['json', 'csv', 'convert', 'excel', 'spreadsheet', 'export'],
    actionLabel: 'To CSV',
    limitations: ['Nested objects are written as JSON text inside the cell.'],
    related: ['csv-to-json', 'json-formatter'],
  }),
  defineTool({
    id: 'csv-viewer',
    name: 'CSV Viewer & Editor',
    description: 'View, sort, filter and edit CSV/TSV files. Clean data, remove duplicates, split or merge columns.',
    category: 'spreadsheets',
    icon: 'Sheet',
    status: 'available',
    inputTypes: ['text/csv', '.csv', '.tsv', 'text/tab-separated-values', '.txt'],
    outputTypes: ['text/csv', 'application/json'],
    intents: ['edit', 'analyze'],
    keywords: ['csv', 'viewer', 'editor', 'grid', 'table', 'clean', 'duplicate rows', 'columns', 'split column', 'merge columns', 'tsv', 'sort', 'filter'],
    aliases: ['csv cleaner', 'duplicate row remover', 'column splitter', 'column merger', 'tsv to csv', 'data formatter'],
    actionLabel: 'View / edit',
    limitations: ['The whole file is loaded into memory; files of a few hundred MB may be slow on phones.'],
    related: ['csv-to-json', 'spreadsheet-viewer', 'json-to-csv'],
  }),
  defineTool({
    id: 'spreadsheet-viewer',
    name: 'Spreadsheet Viewer',
    description: 'Open Excel and OpenDocument spreadsheets, browse sheets and export them to CSV or JSON.',
    category: 'spreadsheets',
    icon: 'Sheet',
    status: 'available',
    inputTypes: ['.xlsx', '.xlsm', '.xls', '.xlsb', '.ods', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel', 'application/vnd.oasis.opendocument.spreadsheet'],
    outputTypes: ['text/csv', 'application/json'],
    intents: ['convert', 'analyze'],
    keywords: ['excel', 'xlsx', 'xls', 'ods', 'spreadsheet', 'viewer', 'excel to csv', 'excel to json', 'metadata', 'sheets'],
    aliases: ['excel viewer', 'xlsx to csv', 'excel to csv', 'spreadsheet metadata viewer'],
    actionLabel: 'Open spreadsheet',
    limitations: ['Charts, images, formatting and macros are not shown; macros never run.', 'Password-protected workbooks are not supported.'],
    related: ['csv-viewer', 'csv-to-json', 'excel-to-pdf'],
  }),
  planned({ id: 'presentation-info', name: 'Presentation Inspector', description: 'View slide count, titles and media inside a PPTX.', category: 'presentations', icon: 'Presentation', inputTypes: ['.pptx'], keywords: ['pptx', 'slides', 'metadata'], reason: 'Scheduled after the data phase.' }),
];

export const calculatorTools = [
  defineTool({
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Percent of a number, percentage change, discounts and profit/loss — with formulas shown.',
    category: 'calculators',
    icon: 'Percent',
    status: 'available',
    intents: ['analyze'],
    keywords: ['percent', 'percentage', 'discount', 'change', 'increase', 'decrease', 'profit', 'loss', 'margin'],
    aliases: ['discount calculator', 'profit loss calculator'],
    related: ['gst-calculator', 'emi-calculator'],
  }),
  defineTool({
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Add or remove GST at Indian slab rates, with CGST/SGST split.',
    category: 'calculators',
    icon: 'Receipt',
    status: 'available',
    intents: ['analyze'],
    keywords: ['gst', 'tax', 'cgst', 'sgst', 'igst', 'india', 'inclusive', 'exclusive'],
    limitations: ['Rates are the common slabs; check current government notifications for your item.'],
    related: ['percentage-calculator', 'emi-calculator'],
  }),
  defineTool({
    id: 'emi-calculator',
    name: 'EMI / Loan Calculator',
    description: 'Monthly instalment, total interest and amortisation schedule for a loan.',
    category: 'calculators',
    icon: 'Landmark',
    status: 'available',
    intents: ['analyze'],
    keywords: ['emi', 'loan', 'mortgage', 'home loan', 'interest', 'amortization', 'instalment'],
    aliases: ['loan calculator'],
    limitations: ['Assumes a fixed rate and monthly reducing balance. Lenders may round differently.'],
    related: ['interest-calculator', 'percentage-calculator'],
  }),
  planned({ id: 'interest-calculator', name: 'Interest Calculator', description: 'Simple and compound interest.', category: 'calculators', icon: 'TrendingUp', keywords: ['simple interest', 'compound interest'], reason: PHASE.productivity }),
  planned({ id: 'scientific-calculator', name: 'Scientific Calculator', description: 'Trigonometry, logs and powers.', category: 'calculators', icon: 'Calculator', keywords: ['calculator', 'scientific', 'basic'], reason: PHASE.productivity }),
  planned({ id: 'date-calculator', name: 'Date & Age Calculator', description: 'Age, days between dates, add/subtract time.', category: 'calculators', icon: 'CalendarDays', keywords: ['age', 'date', 'days between', 'time'], reason: PHASE.productivity }),
  planned({ id: 'bmi-calculator', name: 'BMI Calculator', description: 'Body mass index.', category: 'calculators', icon: 'Activity', keywords: ['bmi', 'body mass'], reason: PHASE.productivity }),
  defineTool({
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Length, area, volume, weight, temperature, speed, time, data, pressure, energy, power, frequency and angle.',
    category: 'converters',
    icon: 'Ruler',
    status: 'available',
    intents: ['convert'],
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'metric', 'imperial', 'km', 'miles', 'kg', 'pounds', 'celsius', 'fahrenheit', 'bytes', 'mb', 'gb', 'pressure', 'bar', 'psi', 'energy', 'power', 'angle'],
    aliases: ['length converter', 'weight converter', 'temperature converter', 'data storage converter'],
    popular: true,
  }),
];

export const fileTools = [
  defineTool({
    id: 'file-info',
    name: 'File Information',
    description: 'Detect the real file type from its contents, and view size, extension and SHA-256.',
    category: 'files',
    icon: 'FileSearch',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    intents: ['analyze'],
    keywords: ['file', 'info', 'mime', 'type', 'extension', 'size', 'detect', 'magic bytes', 'duplicate'],
    aliases: ['mime type detector', 'file size analyzer', 'extension detector', 'duplicate file finder'],
    actionLabel: 'File info',
    limitations: ['Duplicate detection compares SHA-256 hashes of the files you add.'],
    related: ['hash-generator', 'zip-creator'],
  }),
  defineTool({
    id: 'zip-creator',
    name: 'Create ZIP',
    description: 'Bundle files into a ZIP archive.',
    category: 'files',
    icon: 'FileArchive',
    status: 'available',
    batch: true,
    inputTypes: ['*/*'],
    outputTypes: ['application/zip'],
    intents: ['compress'],
    keywords: ['zip', 'archive', 'compress', 'bundle'],
    actionLabel: 'Add to ZIP',
    limitations: ['Password-protected ZIPs are not supported.'],
    related: ['zip-extractor', 'file-info'],
  }),
  defineTool({
    id: 'zip-extractor',
    name: 'Extract ZIP',
    description: 'Open a ZIP archive and download individual files.',
    category: 'files',
    icon: 'PackageOpen',
    status: 'available',
    inputTypes: ['application/zip', '.zip'],
    intents: ['convert'],
    keywords: ['unzip', 'extract', 'zip', 'archive', 'open'],
    actionLabel: 'Extract',
    limitations: ['Encrypted ZIP files and ZIP64 archives over ~2 GB are not supported.', 'The whole archive is loaded into memory.'],
    related: ['zip-creator', 'file-info'],
  }),
];
