import { defineTool, planned, PDF, PHASE } from './define';

const pdfHelp = {
  problems: [
    'Password-protected (encrypted) PDFs cannot be modified. Remove the password in the app that created it, using your own password.',
    'Damaged PDFs may fail to open. Re-saving the file from a PDF viewer often repairs it.',
  ],
  fileSize: 'PDFs up to around 200 MB usually work on desktop. Phones have far less memory — keep files under about 50 MB there.',
  browsers: 'Works in all modern browsers.',
  troubleshooting: ['Check the file opens in a normal PDF viewer.', 'Try a smaller file.', 'Reload the page and try again.'],
};

const pdfLimitations = ['Encrypted PDFs are not supported.', 'Digital signatures in the source PDF become invalid after modification.'];

export const pdfTools = [
  defineTool({
    id: 'pdf-merge',
    name: 'Merge PDF',
    description: 'Combine several PDFs into one document, in the order you choose.',
    category: 'pdf',
    icon: 'Combine',
    status: 'available',
    batch: true,
    inputTypes: PDF,
    outputTypes: PDF,
    intents: ['edit'],
    keywords: ['merge', 'combine', 'join', 'append', 'pdf'],
    actionLabel: 'Merge',
    limitations: [...pdfLimitations, 'Bookmarks (outline) of the source files are not carried over.'],
    related: ['pdf-split', 'pdf-rotate', 'image-to-pdf'],
    help: pdfHelp,
    popular: true,
  }),
  defineTool({
    id: 'pdf-split',
    name: 'Split / Extract Pages',
    description: 'Extract page ranges into a new PDF, or split every page into its own file.',
    category: 'pdf',
    icon: 'Scissors',
    status: 'available',
    inputTypes: PDF,
    outputTypes: PDF,
    intents: ['edit'],
    keywords: ['split', 'extract', 'pages', 'range', 'separate', 'pdf'],
    aliases: ['extract pdf pages', 'pdf splitter'],
    actionLabel: 'Split / Extract',
    limitations: pdfLimitations,
    related: ['pdf-merge', 'pdf-delete-pages', 'pdf-rotate'],
    help: pdfHelp,
    popular: true,
  }),
  defineTool({
    id: 'pdf-rotate',
    name: 'Rotate PDF',
    description: 'Rotate all pages, or selected pages, of a PDF.',
    category: 'pdf',
    icon: 'RotateCw',
    status: 'available',
    inputTypes: PDF,
    outputTypes: PDF,
    intents: ['edit'],
    keywords: ['rotate', 'turn', 'orientation', 'landscape', 'portrait', 'pdf'],
    actionLabel: 'Rotate',
    limitations: pdfLimitations,
    related: ['pdf-split', 'pdf-merge'],
    help: pdfHelp,
  }),
  defineTool({
    id: 'pdf-delete-pages',
    name: 'Delete PDF Pages',
    description: 'Remove selected pages from a PDF.',
    category: 'pdf',
    icon: 'FileMinus',
    status: 'available',
    inputTypes: PDF,
    outputTypes: PDF,
    intents: ['edit'],
    keywords: ['delete', 'remove', 'pages', 'pdf'],
    actionLabel: 'Delete pages',
    limitations: pdfLimitations,
    related: ['pdf-split', 'pdf-merge'],
    help: pdfHelp,
  }),
  defineTool({
    id: 'pdf-metadata',
    name: 'PDF Metadata',
    description: 'View document properties and page sizes, and remove identifying metadata.',
    category: 'pdf',
    icon: 'FileSearch',
    status: 'available',
    inputTypes: PDF,
    outputTypes: PDF,
    intents: ['analyze'],
    keywords: ['metadata', 'properties', 'author', 'title', 'info', 'remove metadata', 'privacy', 'pages'],
    aliases: ['pdf info', 'pdf page information', 'remove pdf metadata'],
    actionLabel: 'Inspect',
    limitations: [...pdfLimitations, 'XMP metadata streams are removed along with the standard fields.'],
    related: ['file-info', 'pdf-split'],
    help: pdfHelp,
  }),
  defineTool({
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Combine JPEG and PNG images into a PDF, one image per page.',
    category: 'pdf',
    icon: 'FileImage',
    status: 'available',
    batch: true,
    inputTypes: ['image/jpeg', 'image/png', 'image/webp'],
    outputTypes: PDF,
    intents: ['convert', 'create'],
    keywords: ['image', 'jpg', 'png', 'photo', 'to pdf', 'convert', 'scan'],
    aliases: ['jpg to pdf', 'png to pdf', 'photos to pdf'],
    actionLabel: 'Create PDF',
    limitations: ['WebP images are converted to PNG before embedding, which may increase size.'],
    related: ['pdf-merge', 'image-compressor'],
    help: pdfHelp,
    popular: true,
  }),
  planned({ id: 'pdf-to-image', name: 'PDF to Image', description: 'Render PDF pages as PNG or JPEG.', category: 'pdf', icon: 'Image', inputTypes: PDF, intents: ['convert'], keywords: ['pdf to jpg', 'pdf to png', 'render'], actionLabel: 'To images', reason: PHASE.pdf }),
  planned({ id: 'pdf-compressor', name: 'Compress PDF', description: 'Reduce PDF file size.', category: 'pdf', icon: 'Minimize2', inputTypes: PDF, intents: ['compress'], keywords: ['compress', 'reduce', 'smaller'], actionLabel: 'Compress', reason: PHASE.pdf }),
  planned({ id: 'pdf-organize', name: 'Reorder PDF Pages', description: 'Drag pages into a new order, duplicate or insert blank pages.', category: 'pdf', icon: 'LayoutGrid', inputTypes: PDF, intents: ['edit'], keywords: ['reorder', 'organize', 'arrange', 'duplicate', 'blank page', 'insert'], actionLabel: 'Reorder', reason: 'Needs page thumbnails, which arrive with the PDF viewer.' }),
  planned({ id: 'pdf-watermark', name: 'PDF Watermark', description: 'Stamp text or an image on PDF pages.', category: 'pdf', icon: 'Stamp', inputTypes: PDF, intents: ['edit'], keywords: ['watermark', 'stamp'], actionLabel: 'Watermark', reason: PHASE.pdf }),
  planned({ id: 'pdf-sign', name: 'Sign PDF', description: 'Draw or place a signature image on a PDF.', category: 'pdf', icon: 'PenTool', inputTypes: PDF, intents: ['edit'], keywords: ['sign', 'signature', 'draw'], actionLabel: 'Sign', reason: PHASE.pdf }),
  planned({ id: 'pdf-page-numbers', name: 'Add Page Numbers', description: 'Number PDF pages.', category: 'pdf', icon: 'ListOrdered', inputTypes: PDF, intents: ['edit'], keywords: ['page numbers', 'numbering'], reason: PHASE.pdf }),
  planned({ id: 'pdf-to-text', name: 'PDF to Text', description: 'Extract the text layer of a PDF.', category: 'pdf', icon: 'FileText', inputTypes: PDF, intents: ['convert'], keywords: ['extract text', 'pdf to txt'], actionLabel: 'Extract text', reason: PHASE.pdf }),
  planned({ id: 'pdf-protect', name: 'Password Protect PDF', description: 'Encrypt a PDF with a password.', category: 'pdf', icon: 'Lock', inputTypes: PDF, keywords: ['password', 'encrypt', 'protect'], reason: 'Needs a vetted client-side PDF encryption engine.' }),
  planned({ id: 'pdf-ocr', name: 'PDF OCR', description: 'Recognise text in scanned PDFs.', category: 'pdf', icon: 'ScanText', inputTypes: PDF, keywords: ['ocr', 'scan', 'recognize'], actionLabel: 'OCR', reason: 'OCR engines are large and accuracy varies; it will ship once quality is verified, including for Hindi.' }),
  planned({ id: 'pdf-compare', name: 'Compare PDFs', description: 'Highlight text differences between two PDFs.', category: 'pdf', icon: 'GitCompare', inputTypes: PDF, keywords: ['compare', 'diff'], reason: PHASE.pdf }),
  planned({ id: 'pdf-to-word', name: 'PDF to Word', description: 'Convert PDF to editable DOCX.', category: 'pdf', icon: 'FileType', inputTypes: PDF, intents: ['convert'], keywords: ['docx', 'word'], reason: PHASE.office }),
  planned({ id: 'pdf-to-excel', name: 'PDF to Excel', description: 'Convert PDF tables to XLSX.', category: 'pdf', icon: 'Sheet', inputTypes: PDF, intents: ['convert'], keywords: ['xlsx', 'excel', 'tables'], reason: PHASE.office }),
  planned({ id: 'pdf-to-powerpoint', name: 'PDF to PowerPoint', description: 'Convert PDF to PPTX.', category: 'pdf', icon: 'Presentation', inputTypes: PDF, intents: ['convert'], keywords: ['pptx', 'powerpoint', 'slides'], reason: PHASE.office }),
  planned({ id: 'word-to-pdf', name: 'Word to PDF', description: 'Convert DOCX to PDF.', category: 'documents', icon: 'FileType', inputTypes: ['.docx'], intents: ['convert'], keywords: ['docx', 'word'], reason: PHASE.office }),
  planned({ id: 'excel-to-pdf', name: 'Excel to PDF', description: 'Convert XLSX to PDF.', category: 'spreadsheets', icon: 'Sheet', inputTypes: ['.xlsx'], intents: ['convert'], keywords: ['xlsx', 'excel'], reason: PHASE.office }),
  planned({ id: 'powerpoint-to-pdf', name: 'PowerPoint to PDF', description: 'Convert PPTX to PDF.', category: 'presentations', icon: 'Presentation', inputTypes: ['.pptx'], intents: ['convert'], keywords: ['pptx', 'powerpoint'], reason: PHASE.office }),
];
