import { defineTool } from './define';

export const generatorTools = [
  defineTool({
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Branded QR codes for links, Wi-Fi, UPI payments, contacts, email, SMS and phone — with your logo, colours, dot and corner styles, and a scan check.',
    category: 'generators',
    icon: 'QrCode',
    status: 'available',
    outputTypes: ['image/png', 'image/svg+xml'],
    intents: ['create'],
    keywords: ['qr', 'qr code', 'generator', 'logo', 'custom qr', 'branded qr', 'wifi qr', 'upi qr', 'vcard', 'url', 'svg', 'png', 'colour', 'design'],
    aliases: ['qr code with logo', 'custom qr code', 'wifi qr code', 'upi qr code generator', 'vcard qr code'],
    limitations: [
      'Logos and low-contrast colours reduce how easily a code scans; the built-in scan check tells you when a design stops reading.',
      'The QR code is static: its content cannot be changed after printing, and there is no scan tracking.',
    ],
    related: ['qr-reader', 'barcode-generator', 'favicon-generator'],
    popular: true,
  }),
  defineTool({
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Create Code 128, EAN-13, EAN-8, UPC-A, Code 39, ITF-14 and Codabar barcodes, with check-digit validation. Download SVG or PNG.',
    category: 'generators',
    icon: 'Barcode',
    status: 'available',
    outputTypes: ['image/svg+xml', 'image/png'],
    intents: ['create'],
    keywords: ['barcode', 'ean', 'ean-13', 'ean13', 'upc', 'code128', 'code 128', 'code39', 'itf-14', 'codabar', 'product barcode', 'label', 'svg'],
    aliases: ['ean-13 barcode generator', 'code 128 generator', 'upc barcode generator'],
    limitations: ['Generating a barcode does not register it: retail EAN/UPC numbers must be licensed from GS1.'],
    related: ['qr-generator', 'qr-reader'],
  }),
];

export const productivityTools = [
  defineTool({
    id: 'notes',
    name: 'Notes',
    description: 'Quick private notes that save automatically in your browser. Search, pin, and export as Markdown or text.',
    category: 'productivity',
    icon: 'StickyNote',
    status: 'available',
    outputTypes: ['text/markdown', 'text/plain', 'application/json'],
    intents: ['create', 'edit'],
    keywords: ['notes', 'notepad', 'note taking', 'memo', 'scratchpad', 'private notes', 'offline notes', 'markdown'],
    aliases: ['online notepad', 'private notepad'],
    limitations: [
      'Notes are stored only in this browser on this device — they are not synced. Export a backup if they matter.',
      'Clearing this site’s data (or “Clear all local data” in Settings) deletes them.',
    ],
    requires: ['indexedDB'],
    related: ['todo-list', 'markdown-editor', 'word-counter'],
  }),
  defineTool({
    id: 'todo-list',
    name: 'To-Do List',
    description: 'A simple private task list with due dates, priorities and filters, saved automatically in your browser.',
    category: 'productivity',
    icon: 'ListChecks',
    status: 'available',
    outputTypes: ['application/json', 'text/csv'],
    intents: ['create', 'edit'],
    keywords: ['todo', 'to-do', 'task list', 'tasks', 'checklist', 'planner', 'reminders', 'productivity'],
    aliases: ['task manager', 'checklist'],
    limitations: [
      'Tasks are stored only in this browser on this device — they are not synced. Export a backup if they matter.',
      'There are no alarms for due dates; overdue tasks are highlighted when you open the list.',
    ],
    requires: ['indexedDB'],
    related: ['notes', 'timer'],
  }),
  defineTool({
    id: 'timer',
    name: 'Timer, Stopwatch & Pomodoro',
    description: 'Countdown timer with sound, stopwatch with laps, and a Pomodoro focus timer.',
    category: 'productivity',
    icon: 'Timer',
    status: 'available',
    intents: ['create'],
    keywords: ['timer', 'countdown', 'stopwatch', 'pomodoro', 'focus', 'alarm', 'lap', 'study timer', 'kitchen timer'],
    aliases: ['online timer', 'online stopwatch', 'pomodoro timer', 'countdown timer'],
    limitations: ['Keep the tab open: closing it stops the timer. Some phones pause pages in the background, which can delay the alarm.'],
    related: ['todo-list', 'date-calculator'],
  }),
];
