import { defineTool, planned, PHASE } from './define';

const TEXT_IN = ['text/plain', '.txt', '.md'];

export const textTools = [
  defineTool({
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, paragraphs and lines, with reading time. Handles Hindi and other Unicode text.',
    category: 'text',
    icon: 'LetterText',
    status: 'available',
    inputTypes: TEXT_IN,
    intents: ['analyze'],
    keywords: ['word count', 'character count', 'sentence', 'paragraph', 'reading time', 'lines', 'hindi', 'counter'],
    aliases: ['character counter', 'reading time calculator', 'sentence counter', 'paragraph counter'],
    actionLabel: 'Count words',
    related: ['case-converter', 'text-cleaner'],
    popular: true,
  }),
  defineTool({
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Change text to UPPER, lower, Title, Sentence, camelCase, snake_case, kebab-case and more.',
    category: 'text',
    icon: 'CaseSensitive',
    status: 'available',
    intents: ['convert'],
    keywords: ['uppercase', 'lowercase', 'title case', 'camel', 'snake', 'kebab', 'capitalize'],
    related: ['slug-generator', 'text-cleaner'],
  }),
  defineTool({
    id: 'text-cleaner',
    name: 'Text Cleaner & Line Tools',
    description: 'Remove duplicate or empty lines, sort, reverse, trim whitespace and fix line breaks.',
    category: 'text',
    icon: 'ListFilter',
    status: 'available',
    inputTypes: TEXT_IN,
    intents: ['edit'],
    keywords: ['duplicate lines', 'remove duplicates', 'sort lines', 'whitespace', 'trim', 'line break', 'empty lines', 'reverse', 'clean'],
    aliases: ['duplicate line remover', 'line sorter', 'whitespace cleaner', 'line-break cleaner', 'reverse text'],
    actionLabel: 'Clean text',
    related: ['find-replace', 'case-converter'],
  }),
  defineTool({
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Find and replace text, with optional case sensitivity and regular expressions.',
    category: 'text',
    icon: 'Replace',
    status: 'available',
    intents: ['edit'],
    keywords: ['find', 'replace', 'search', 'substitute', 'regex'],
    related: ['text-cleaner', 'regex-tester'],
  }),
  defineTool({
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Turn titles into clean URL slugs.',
    category: 'text',
    icon: 'Link2',
    status: 'available',
    intents: ['convert'],
    keywords: ['slug', 'url', 'permalink', 'seo'],
    limitations: ['Non-Latin scripts such as Hindi are kept as Unicode, which modern URLs support; choose "ASCII only" to drop them.'],
    related: ['case-converter', 'url-encoder'],
  }),
  defineTool({
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder paragraphs, sentences or words.',
    category: 'text',
    icon: 'Pilcrow',
    status: 'available',
    intents: ['create'],
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy text', 'filler', 'random text'],
    related: ['word-counter'],
  }),
  planned({ id: 'text-diff', name: 'Text Diff', description: 'Compare two texts side by side.', category: 'text', icon: 'GitCompare', keywords: ['diff', 'compare', 'difference'], reason: PHASE.data }),
  planned({ id: 'markdown-editor', name: 'Markdown Editor', description: 'Write Markdown with live preview and export to HTML.', category: 'documents', icon: 'FileCode', inputTypes: ['.md', 'text/markdown'], keywords: ['markdown', 'md', 'editor', 'preview', 'markdown to html'], reason: 'Needs an HTML sanitiser for safe preview; scheduled for the text & data phase.' }),
  planned({ id: 'markdown-to-pdf', name: 'Markdown to PDF', description: 'Export Markdown as PDF.', category: 'documents', icon: 'FileText', inputTypes: ['.md'], keywords: ['markdown', 'pdf'], reason: PHASE.data }),
  planned({ id: 'text-to-pdf', name: 'Text to PDF', description: 'Convert plain text (including Hindi) to PDF.', category: 'documents', icon: 'FileText', inputTypes: TEXT_IN, keywords: ['txt', 'pdf'], reason: 'Hindi and other Indic scripts need an embedded font with correct shaping; being verified.' }),
  planned({ id: 'rich-text-editor', name: 'Rich Text Editor', description: 'Format documents and export them.', category: 'documents', icon: 'FilePen', keywords: ['editor', 'document', 'rich text'], reason: PHASE.productivity }),
];
