import { defineTool, planned, PHASE } from './define';

const TEXT_IN = ['text/plain', '.txt', '.md'];

export const textTools = [
  defineTool({
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, paragraphs and lines, with reading time. Handles Hindi and other Unicode text.',
    category: 'text',
    icon: 'LetterText',
    status: 'available',
    inputTypes: TEXT_IN,
    intents: ['analyze'],
    keywords: ['word count', 'character count', 'sentence', 'paragraph', 'reading time', 'lines', 'hindi', 'counter'],
    aliases: ['character counter', 'reading time calculator', 'sentence counter', 'paragraph counter'],
    actionLabel: 'Count words',
    related: ['case-converter', 'text-cleaner'],
    popular: true,
  }),
  defineTool({
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Change text to UPPER, lower, Title, Sentence, camelCase, snake_case, kebab-case and more.',
    category: 'text',
    icon: 'CaseSensitive',
    status: 'available',
    intents: ['convert'],
    keywords: ['uppercase', 'lowercase', 'title case', 'camel', 'snake', 'kebab', 'capitalize'],
    related: ['slug-generator', 'text-cleaner'],
  }),
  defineTool({
    id: 'text-cleaner',
    name: 'Text Cleaner & Line Tools',
    description: 'Remove duplicate or empty lines, sort, reverse, trim whitespace and fix line breaks.',
    category: 'text',
    icon: 'ListFilter',
    status: 'available',
    inputTypes: TEXT_IN,
    intents: ['edit'],
    keywords: ['duplicate lines', 'remove duplicates', 'sort lines', 'whitespace', 'trim', 'line break', 'empty lines', 'reverse', 'clean'],
    aliases: ['duplicate line remover', 'line sorter', 'whitespace cleaner', 'line-break cleaner', 'reverse text'],
    actionLabel: 'Clean text',
    related: ['find-replace', 'case-converter'],
  }),
  defineTool({
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Find and replace text, with optional case sensitivity and regular expressions.',
    category: 'text',
    icon: 'Replace',
    status: 'available',
    intents: ['edit'],
    keywords: ['find', 'replace', 'search', 'substitute', 'regex'],
    related: ['text-cleaner', 'regex-tester'],
  }),
  defineTool({
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Turn titles into clean URL slugs.',
    category: 'text',
    icon: 'Link2',
    status: 'available',
    intents: ['convert'],
    keywords: ['slug', 'url', 'permalink', 'seo'],
    limitations: ['Non-Latin scripts such as Hindi are kept as Unicode, which modern URLs support; choose "ASCII only" to drop them.'],
    related: ['case-converter', 'url-encoder'],
  }),
  defineTool({
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder paragraphs, sentences or words.',
    category: 'text',
    icon: 'Pilcrow',
    status: 'available',
    intents: ['create'],
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy text', 'filler', 'random text'],
    related: ['word-counter'],
  }),
  defineTool({
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts or files line by line, word by word or character by character.',
    category: 'text',
    icon: 'GitCompare',
    status: 'available',
    inputTypes: ['text/plain', '.txt', '.md', '.json', '.csv', '.xml', '.html', '.css', '.js', '.ts', '.yaml', '.yml'],
    intents: ['analyze'],
    keywords: ['diff', 'compare', 'difference', 'changes', 'patch', 'side by side'],
    aliases: ['compare text', 'text compare', 'diff checker'],
    actionLabel: 'Compare',
    limitations: ['Texts over 2 million characters combined are not compared, to keep the page responsive.'],
    related: ['find-replace', 'text-cleaner', 'json-formatter'],
  }),
  defineTool({
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write Markdown with a live preview, then export Markdown, HTML or PDF.',
    category: 'documents',
    icon: 'FileCode',
    status: 'available',
    inputTypes: ['.md', '.markdown', 'text/markdown'],
    outputTypes: ['text/markdown', 'text/html', 'application/pdf'],
    intents: ['edit', 'create', 'convert'],
    keywords: ['markdown', 'md', 'editor', 'preview', 'markdown to html', 'gfm', 'readme'],
    aliases: ['markdown to html', 'md editor'],
    actionLabel: 'Edit Markdown',
    limitations: ['HTML inside Markdown is sanitised: scripts, event handlers and unsafe links are removed.'],
    related: ['markdown-to-pdf', 'code-formatter', 'word-counter'],
  }),
  defineTool({
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    description: 'Turn Markdown into a clean PDF using your browser’s print engine, with Hindi support.',
    category: 'documents',
    icon: 'FileText',
    status: 'available',
    inputTypes: ['.md', '.markdown', 'text/markdown'],
    outputTypes: ['application/pdf'],
    intents: ['convert'],
    keywords: ['markdown', 'pdf', 'md to pdf', 'convert', 'print'],
    actionLabel: 'To PDF',
    limitations: ['Uses the browser print dialog: choose “Save as PDF”. Headers and footers added by the browser can be turned off in that dialog.'],
    related: ['markdown-editor', 'text-to-pdf', 'image-to-pdf'],
  }),
  defineTool({
    id: 'text-to-pdf',
    name: 'Text to PDF',
    description: 'Convert plain text — including Hindi and other Indian languages — to PDF.',
    category: 'documents',
    icon: 'FileText',
    status: 'available',
    inputTypes: ['text/plain', '.txt', '.md', '.log', '.csv'],
    outputTypes: ['application/pdf'],
    intents: ['convert'],
    keywords: ['txt to pdf', 'text', 'pdf', 'hindi', 'convert', 'print'],
    actionLabel: 'To PDF',
    limitations: ['Uses the browser print dialog: choose “Save as PDF”.', 'Text renders with fonts installed on your device.'],
    related: ['markdown-to-pdf', 'word-counter', 'image-to-pdf'],
  }),
  planned({ id: 'rich-text-editor', name: 'Rich Text Editor', description: 'Format documents and export them.', category: 'documents', icon: 'FilePen', keywords: ['editor', 'document', 'rich text'], reason: PHASE.productivity }),
];
