/**
 * Task landing pages: one page per common search ("compress image to 20 KB",
 * "JPG to PDF", "UPI QR code"), each running the right tool with the right
 * settings already chosen, plus content written for that specific need.
 *
 * Rules: only promise what the tool really does; every page has its own
 * heading, introduction, steps and FAQ (no copy-paste pages); Hindi pages are
 * real translations linked with hreflang to their English twin.
 */
import type { ToolPreset } from '@/types/tool';
import type { Faq } from './seo';

export interface Task {
  slug: string;
  lang: 'en' | 'hi';
  toolId: string;
  preset?: ToolPreset;
  /** <title> without the brand. */
  title: string;
  h1: string;
  description: string;
  intro: string;
  steps: string[];
  faqs: Faq[];
  /** Slug of the same page in the other language. */
  twin?: string;
  related?: string[];
  keywords: string[];
}

const KB = (n: number): Partial<Task> & Pick<Task, 'slug' | 'title' | 'h1' | 'description' | 'intro' | 'faqs' | 'keywords'> => ({
  slug: `compress-image-to-${n}kb`,
  title: `Compress Image to ${n} KB Online — Free, No Upload`,
  h1: `Compress an image to ${n} KB`,
  description: `Reduce a photo or JPG to under ${n} KB in your browser for online forms and uploads. Free, no sign-up, and the image never leaves your device.`,
  intro: `Many application portals reject photos bigger than ${n} KB. Choose your image and this page shrinks it to just under ${n} KB: it lowers JPEG quality only as much as needed and, if that is not enough, reduces the dimensions a little. You see the final size before you download.`,
  faqs: [
    { q: `Will my photo be exactly ${n} KB?`, a: `It will be just under ${n} KB (counted as ${n * 1000} bytes, so it also passes portals that count 1 KB as 1024 bytes). The tool keeps the highest quality that fits.` },
    { q: 'What if the photo still looks too blurry?', a: `Crop away the background first so the face or signature fills more of the picture, then compress again. Very large limits like ${n} KB rarely need the dimensions changed.` },
    { q: 'Do I need to change the format?', a: 'Forms usually want JPG/JPEG, which this page produces by default. PNG cannot be compressed by quality, only by size.' },
  ],
  keywords: [`compress image to ${n}kb`, `reduce photo size to ${n} kb`, `jpg ${n}kb`, `image size ${n}kb`, `photo ${n}kb converter`],
});

const compressSteps = (n: number) => [`Choose or drop your photo (JPG, PNG or WebP).`, `The target is already set to ${n} KB — press “Process”.`, 'Check the new size, then download your image.'];

export const TASKS: Task[] = [
  /* ---------- Image size (exam and government forms) ---------- */
  ...[20, 50, 100, 200].map(
    (n) =>
      ({
        ...KB(n),
        lang: 'en',
        toolId: 'image-compressor',
        preset: { targetKb: n, format: 'image/jpeg' },
        steps: compressSteps(n),
        related: ['reduce-photo-size-in-kb', 'compress-signature-for-online-form', 'jpg-to-pdf'],
        twin: n === 20 ? 'hi/photo-20kb-kaise-kare' : undefined,
      }) as Task,
  ),
  {
    slug: 'reduce-photo-size-in-kb',
    lang: 'en',
    toolId: 'image-compressor',
    preset: { targetKb: 50, format: 'image/jpeg' },
    title: 'Reduce Photo Size in KB — Any Target Size, Free',
    h1: 'Reduce photo size in KB',
    description: 'Make a photo smaller in KB for online forms, email or WhatsApp: pick any target (20, 50, 100 KB…). Works in your browser — no upload, no sign-up.',
    intro: 'Type the size you need or tap a preset, and the photo is compressed to just under it. Quality is lowered only as far as necessary, and dimensions are reduced only when quality alone cannot reach the target. Several photos can be done at once and downloaded as a ZIP.',
    steps: ['Add one or more photos.', 'Set the target size in KB (preset: 50 KB).', 'Press “Process” and download the results.'],
    faqs: [
      { q: 'How do I check the size of my photo?', a: 'The original and new sizes are shown next to each file after processing. On a computer you can also right-click the file and choose Properties.' },
      { q: 'Can I compress many photos together?', a: 'Yes. Add as many as you like; each is compressed to the target and you can download them all as a ZIP.' },
      { q: 'Is my photo uploaded?', a: 'No. Everything happens inside your browser, so it also works for private documents.' },
    ],
    twin: 'hi/photo-ka-size-kam-kare',
    related: ['compress-image-to-20kb', 'compress-image-to-50kb', 'compress-image-to-100kb'],
    keywords: ['reduce photo size in kb', 'reduce image size', 'photo size reducer', 'image compressor in kb', 'compress photo'],
  },
  {
    slug: 'compress-signature-for-online-form',
    lang: 'en',
    toolId: 'image-compressor',
    preset: { targetKb: 20, format: 'image/jpeg' },
    title: 'Compress Signature Image for Online Forms (10–20 KB)',
    h1: 'Compress a signature for an online form',
    description: 'Shrink a scanned or photographed signature to 10–20 KB JPG for exam, bank and government forms. Free, private, in your browser.',
    intro: 'Signature uploads usually need a small JPG, often between 10 and 20 KB. Sign in black or dark-blue ink on plain white paper, photograph or scan it, crop tightly around the signature, then compress it here. The target is set to 20 KB; type 10 if your form asks for less.',
    steps: ['Crop the photo so only the signature is left (use the Crop Image tool if needed).', 'Add the cropped image here — the target is 20 KB.', 'Press “Process” and download the JPG.'],
    faqs: [
      { q: 'Why is my signature rejected even under 20 KB?', a: 'Forms often also check pixel dimensions (for example 140 × 60) or a minimum size such as 10 KB. Use Resize Image for exact dimensions, and do not compress far below the minimum.' },
      { q: 'How do I make the background white?', a: 'Use plain white paper and good light. Cropping close to the ink also removes shadows.' },
    ],
    twin: 'hi/signature-ka-size-kam-kare',
    related: ['compress-image-to-20kb', 'resize-image-for-instagram', 'reduce-photo-size-in-kb'],
    keywords: ['compress signature', 'signature size reducer', 'signature 20kb', 'signature 10kb', 'signature resize for online form'],
  },
  {
    slug: 'resize-image-for-instagram',
    lang: 'en',
    toolId: 'image-resizer',
    preset: { width: 1080, keepAspect: true },
    title: 'Resize Image for Instagram (1080 px) — Free Online',
    h1: 'Resize images for Instagram',
    description: 'Resize photos to 1080 px wide for Instagram posts without stretching. Batch resize in your browser — no upload, no watermark.',
    intro: 'Instagram shows feed images at 1080 pixels wide. Uploading exactly that width avoids Instagram’s own re-compression of very large photos. The width is preset to 1080 px and the aspect ratio is kept, so nothing is stretched.',
    steps: ['Add your photos.', 'Width is set to 1080 px with the aspect ratio kept — change it for stories (1080 × 1920).', 'Process and download.'],
    faqs: [
      { q: 'What sizes does Instagram use?', a: 'Square 1080 × 1080, portrait 1080 × 1350 and stories/reels 1080 × 1920. Crop to the shape you want first if your photo has a different ratio.' },
      { q: 'Will resizing reduce quality?', a: 'Making a photo smaller keeps it sharp. The output quality can be adjusted before processing.' },
    ],
    related: ['reduce-photo-size-in-kb', 'compress-image-to-200kb'],
    keywords: ['resize image for instagram', 'instagram photo size', '1080 px resize', 'resize photo online'],
  },

  /* ---------- Conversions ---------- */
  {
    slug: 'jpg-to-pdf',
    lang: 'en',
    toolId: 'image-to-pdf',
    title: 'JPG to PDF Converter — Free, No Upload, No Watermark',
    h1: 'Convert JPG to PDF',
    description: 'Turn one or many JPG photos into a single PDF. Reorder pages, choose page size and margins. Free, no watermark, files never leave your device.',
    intro: 'Add your JPG images, drag them into the right order and create one PDF — useful for scanned documents, marksheets and receipts. Pages can match each image or use A4/Letter with margins. Nothing is uploaded.',
    steps: ['Add your JPG files (several at once is fine).', 'Drag to reorder and pick a page size.', 'Create the PDF and download it.'],
    faqs: [
      { q: 'Can I combine several JPGs into one PDF?', a: 'Yes — every image becomes a page, in the order you choose.' },
      { q: 'Is there a watermark or page limit?', a: 'No watermark and no artificial limit; very large batches are limited only by your device’s memory.' },
    ],
    twin: 'hi/jpg-se-pdf',
    related: ['combine-images-into-pdf', 'pdf-to-jpg', 'compress-image-to-100kb'],
    keywords: ['jpg to pdf', 'jpeg to pdf', 'convert jpg to pdf', 'photo to pdf', 'image to pdf free'],
  },
  {
    slug: 'combine-images-into-pdf',
    lang: 'en',
    toolId: 'image-to-pdf',
    title: 'Combine Images into One PDF — JPG, PNG, WebP',
    h1: 'Combine images into one PDF',
    description: 'Merge JPG, PNG and WebP images into a single PDF document in the order you want. Free and private — processing happens in your browser.',
    intro: 'Photographed pages of a document, a set of screenshots, or ID card front and back: add them all, arrange the order, and save one tidy PDF that is easy to email or upload.',
    steps: ['Add all the images.', 'Arrange the order and margins.', 'Create and download the PDF.'],
    faqs: [
      { q: 'Can I mix PNG and JPG?', a: 'Yes. JPG, PNG and WebP can be combined in the same PDF.' },
      { q: 'How do I make the PDF smaller?', a: 'Compress the images first (for example to 200 KB each), then combine them.' },
    ],
    related: ['jpg-to-pdf', 'png-to-pdf', 'compress-image-to-200kb'],
    keywords: ['combine images into pdf', 'merge photos into pdf', 'multiple images to one pdf', 'png and jpg to pdf'],
  },
  {
    slug: 'png-to-pdf',
    lang: 'en',
    toolId: 'image-to-pdf',
    title: 'PNG to PDF Converter — Free, Keeps Quality',
    h1: 'Convert PNG to PDF',
    description: 'Convert PNG images and screenshots to PDF without losing sharpness. Free, no sign-up, no upload.',
    intro: 'PNG screenshots, diagrams and scans keep their crisp edges when placed into a PDF here. Combine several into one document and choose a page size.',
    steps: ['Add PNG files.', 'Choose the page size and order.', 'Download the PDF.'],
    faqs: [{ q: 'Does transparency stay transparent?', a: 'PDF pages are white, so transparent areas appear white in the PDF.' }],
    related: ['jpg-to-pdf', 'combine-images-into-pdf'],
    keywords: ['png to pdf', 'convert png to pdf', 'screenshot to pdf'],
  },
  {
    slug: 'pdf-to-jpg',
    lang: 'en',
    toolId: 'pdf-to-image',
    preset: { format: 'image/jpeg' },
    title: 'PDF to JPG Converter — Every Page as an Image',
    h1: 'Convert PDF to JPG',
    description: 'Save each PDF page as a JPG image at 72, 150 or 300 dpi. Free, no upload — your PDF stays on your device.',
    intro: 'Pick a PDF and every page (or the ones you choose) is turned into a JPG. 150 dpi suits screens and sharing; 300 dpi suits printing. Several pages download together as a ZIP.',
    steps: ['Choose your PDF.', 'JPG is preselected — pick the resolution and pages.', 'Convert and download the images.'],
    faqs: [
      { q: 'Can I convert only one page?', a: 'Yes — select just the pages you need before converting.' },
      { q: 'Which resolution should I choose?', a: '150 dpi for WhatsApp, email and websites; 300 dpi for printing. Higher resolution means bigger files.' },
    ],
    twin: 'hi/pdf-se-jpg',
    related: ['pdf-to-png', 'jpg-to-pdf', 'extract-pages-from-pdf'],
    keywords: ['pdf to jpg', 'pdf to jpeg', 'convert pdf to image', 'pdf page to jpg'],
  },
  {
    slug: 'pdf-to-png',
    lang: 'en',
    toolId: 'pdf-to-image',
    preset: { format: 'image/png' },
    title: 'PDF to PNG Converter — Sharp Images of Each Page',
    h1: 'Convert PDF to PNG',
    description: 'Convert PDF pages to lossless PNG images for slides, documents and editing. Free and private.',
    intro: 'PNG keeps text and line drawings perfectly sharp, which makes it the better choice for diagrams, invoices and pages you will edit later.',
    steps: ['Choose your PDF.', 'PNG is preselected — pick resolution and pages.', 'Convert and download.'],
    faqs: [{ q: 'PNG or JPG?', a: 'PNG for text and drawings (sharp, larger files); JPG for photos (smaller files).' }],
    related: ['pdf-to-jpg', 'png-to-pdf'],
    keywords: ['pdf to png', 'convert pdf to png', 'pdf page to png'],
  },
  {
    slug: 'extract-pages-from-pdf',
    lang: 'en',
    toolId: 'pdf-split',
    title: 'Extract Pages from PDF — Free, No Upload',
    h1: 'Extract pages from a PDF',
    description: 'Pick the pages you need and save them as a new PDF, or split a PDF into separate files. Free, in your browser, no upload.',
    intro: 'Need only the first page of a certificate or a few pages of a long report? Select pages from the thumbnails or type ranges like 1-3, 7 and save them as a new PDF. The original file is not changed.',
    steps: ['Choose the PDF.', 'Select pages or type ranges (e.g. 1-3, 7).', 'Save the extracted pages.'],
    faqs: [{ q: 'Can I split every page into its own file?', a: 'Yes — choose to split into single pages and they download together as a ZIP.' }],
    related: ['pdf-to-jpg', 'jpg-to-pdf'],
    keywords: ['extract pages from pdf', 'split pdf', 'separate pdf pages', 'save one page of pdf'],
  },
  {
    slug: 'excel-to-csv',
    lang: 'en',
    toolId: 'spreadsheet-viewer',
    title: 'Excel to CSV Converter — XLSX to CSV, Free',
    h1: 'Convert Excel to CSV',
    description: 'Open XLSX, XLS or ODS files, pick a sheet and export it as CSV. Free, private, works offline — no upload.',
    intro: 'Open the workbook, choose the sheet you need and export it as CSV for databases, imports and scripts. Formulas are exported as their calculated values; macros never run.',
    steps: ['Open the Excel file.', 'Pick the sheet.', 'Export as CSV.'],
    faqs: [{ q: 'Are all sheets exported?', a: 'CSV holds one table, so each sheet is exported separately — choose the sheet you want.' }],
    related: ['excel-to-json'],
    keywords: ['excel to csv', 'xlsx to csv', 'convert excel to csv', 'xls to csv'],
  },
  {
    slug: 'excel-to-json',
    lang: 'en',
    toolId: 'spreadsheet-viewer',
    title: 'Excel to JSON Converter — XLSX to JSON Online',
    h1: 'Convert Excel to JSON',
    description: 'Turn an Excel sheet into JSON (one object per row, using the header row as keys). Free and private, in your browser.',
    intro: 'Developers and analysts often need spreadsheet data as JSON. Open the workbook, choose a sheet and export it — the first row becomes the field names.',
    steps: ['Open the Excel file.', 'Pick the sheet.', 'Export as JSON.'],
    faqs: [{ q: 'What if my sheet has no header row?', a: 'Add one first: the first row is used for the JSON keys.' }],
    related: ['excel-to-csv'],
    keywords: ['excel to json', 'xlsx to json', 'convert excel to json'],
  },

  /* ---------- QR codes ---------- */
  {
    slug: 'upi-qr-code-generator',
    lang: 'en',
    toolId: 'qr-generator',
    preset: { kind: 'upi' },
    title: 'UPI QR Code Generator — Free Payment QR for Shops',
    h1: 'Create a UPI payment QR code',
    description: 'Make a UPI QR code for Google Pay, PhonePe, Paytm and BHIM with an optional fixed amount. Add your shop logo and colours. Free, made on your device.',
    intro: 'Enter your UPI ID (like shopname@okaxis) and name, optionally a fixed amount and note, and print the code at your counter. Any UPI app can scan it. Add your logo and a “Pay with UPI” caption to match your brand.',
    steps: ['UPI is preselected — enter your UPI ID and name.', 'Optionally add an amount, logo and caption.', 'Scan it once with your own phone, then download and print.'],
    faqs: [
      { q: 'Is this the same as a merchant QR from my bank?', a: 'It works with every UPI app for receiving payments to your UPI ID. Merchant QR codes from banks can add settlement reports and soundbox alerts, which a plain UPI QR does not.' },
      { q: 'Is it safe?', a: 'The code only contains your UPI ID and name — no PIN or bank details. Payers always see your name in their app before paying.' },
    ],
    twin: 'hi/upi-qr-code-banaye',
    related: ['qr-code-with-logo', 'wifi-qr-code-generator'],
    keywords: ['upi qr code generator', 'upi qr', 'payment qr code', 'google pay qr', 'phonepe qr code', 'shop qr code'],
  },
  {
    slug: 'qr-code-with-logo',
    lang: 'en',
    toolId: 'qr-generator',
    title: 'QR Code with Logo — Free Custom QR Code Generator',
    h1: 'Create a QR code with your logo',
    description: 'Free custom QR codes with your logo in the middle, brand colours, rounded or dot styles and a “Scan me” frame. Every design is checked to make sure it still scans.',
    intro: 'Upload your logo and pick colours, dot and corner styles. Error correction is raised automatically so the code stays readable with the logo on top, and a built-in scan check warns you if a design stops working. Download SVG for print or PNG up to 4096 px.',
    steps: ['Enter the link or content.', 'Add your logo and choose colours and styles.', 'Wait for “Scan check passed”, then download.'],
    faqs: [
      { q: 'Does a logo stop the QR code working?', a: 'Not if it is small enough: QR codes can lose up to 30% of their data and still be read. The scan check confirms each design decodes correctly.' },
      { q: 'Do these QR codes expire?', a: 'No. They are static codes with no tracking or redirect service in between, so they work forever.' },
    ],
    related: ['upi-qr-code-generator', 'wifi-qr-code-generator', 'vcard-qr-code-generator'],
    keywords: ['qr code with logo', 'custom qr code', 'qr code generator free', 'branded qr code', 'qr code design'],
  },
  {
    slug: 'wifi-qr-code-generator',
    lang: 'en',
    toolId: 'qr-generator',
    preset: { kind: 'wifi' },
    title: 'Wi-Fi QR Code Generator — Share Wi-Fi Without Typing',
    h1: 'Create a Wi-Fi QR code',
    description: 'Let guests join your Wi-Fi by scanning a QR code — no password typing. Works with iPhone and Android cameras. Made on your device; the password is never sent anywhere.',
    intro: 'Enter the network name and password, print the code and stick it near the router or reception. Phone cameras offer to join the network as soon as they see it.',
    steps: ['Wi-Fi is preselected — enter the network name and password.', 'Choose a style or caption such as “Scan for Wi-Fi”.', 'Download and print.'],
    faqs: [{ q: 'Is it safe to print my Wi-Fi password as a QR code?', a: 'Anyone who scans it can join, exactly as if you told them the password. Use a guest network for visitors when possible.' }],
    related: ['qr-code-with-logo', 'upi-qr-code-generator'],
    keywords: ['wifi qr code', 'wifi qr code generator', 'share wifi qr', 'wifi password qr'],
  },
  {
    slug: 'vcard-qr-code-generator',
    lang: 'en',
    toolId: 'qr-generator',
    preset: { kind: 'vcard' },
    title: 'vCard QR Code Generator — Contact QR for Business Cards',
    h1: 'Create a contact (vCard) QR code',
    description: 'Put your name, phone, email and website in a QR code that saves straight to contacts. Ideal for business cards. Free and private.',
    intro: 'Fill in your details and print the code on your business card or ID badge. Scanning it offers to save you as a new contact — no typing mistakes.',
    steps: ['Contact is preselected — fill in your details.', 'Style it with your brand colours or logo.', 'Download SVG for print.'],
    faqs: [{ q: 'Can I update the details later?', a: 'The details are inside the code itself, so a change needs a new code. That also means there is no service that can stop working.' }],
    related: ['qr-code-with-logo'],
    keywords: ['vcard qr code', 'contact qr code', 'business card qr code'],
  },

  /* ---------- Calculators ---------- */
  {
    slug: 'age-calculator',
    lang: 'en',
    toolId: 'date-calculator',
    preset: { mode: 'age' },
    title: 'Age Calculator — Exact Age in Years, Months and Days',
    h1: 'Age calculator',
    description: 'Find your exact age in years, months and days on any date, plus total days and your next birthday. Free and instant.',
    intro: 'Enter a date of birth to get the exact age today or on any other date — useful for exam eligibility cut-offs, which are often calculated “as on” a specific date.',
    steps: ['Enter the date of birth.', 'Change “Age on” for an eligibility date if needed.', 'Read the age, total days and next birthday.'],
    faqs: [
      { q: 'How is age calculated for exams?', a: 'Notifications state an “as on” date. Set “Age on” to that date to see the exact age the authority will use.' },
      { q: 'What about birthdays on 29 February?', a: 'In common years the birthday is counted on 28 February.' },
    ],
    twin: 'hi/umar-calculator',
    related: ['days-between-dates'],
    keywords: ['age calculator', 'calculate age', 'age in years months days', 'date of birth calculator', 'age as on date'],
  },
  {
    slug: 'days-between-dates',
    lang: 'en',
    toolId: 'date-calculator',
    preset: { mode: 'diff' },
    title: 'Days Between Two Dates — Including Working Days',
    h1: 'Days between two dates',
    description: 'Count days, weeks, months and working days (Monday–Friday) between two dates. Optionally include the end date. Free.',
    intro: 'Count the days for notice periods, leave, rent or project deadlines. Working days exclude Saturdays and Sundays (public holidays are not removed).',
    steps: ['Pick the start and end dates.', 'Choose whether to include the end date.', 'Read days, weeks and working days.'],
    faqs: [{ q: 'Should I include the end date?', a: 'Include it when both the first and last day count, as for leave or hotel stays.' }],
    related: ['age-calculator'],
    keywords: ['days between dates', 'date difference', 'working days calculator', 'count days'],
  },
  {
    slug: 'home-loan-emi-calculator',
    lang: 'en',
    toolId: 'emi-calculator',
    preset: { amount: 3000000, rate: 8.5, years: 20 },
    title: 'Home Loan EMI Calculator with Amortisation Schedule',
    h1: 'Home loan EMI calculator',
    description: 'Calculate your monthly home loan EMI, total interest and the full month-by-month schedule. Download the schedule as CSV. Free.',
    intro: 'Enter the loan amount, interest rate and tenure to see the EMI and how much of each payment goes to interest. Home loans are usually 15–30 years, so the schedule shows how slowly the principal falls in the early years.',
    steps: ['Enter loan amount, rate and tenure (example: ₹30 lakh, 8.5%, 20 years).', 'Read the EMI and total interest.', 'Download the schedule if you need it.'],
    faqs: [{ q: 'Does the calculator include processing fees or insurance?', a: 'No — it shows principal and interest only. Lenders may also round the EMI differently.' }],
    related: ['car-loan-emi-calculator', 'fd-calculator'],
    keywords: ['home loan emi calculator', 'housing loan emi', 'emi calculator', 'loan amortization schedule'],
  },
  {
    slug: 'car-loan-emi-calculator',
    lang: 'en',
    toolId: 'emi-calculator',
    preset: { amount: 800000, rate: 9.5, years: 5 },
    title: 'Car Loan EMI Calculator — Monthly Payment & Interest',
    h1: 'Car loan EMI calculator',
    description: 'Work out the monthly EMI and total interest on a car loan, with the full repayment schedule. Free and instant.',
    intro: 'Car loans are typically 3–7 years. Compare tenures to see the trade-off: a longer loan lowers the EMI but raises the total interest you pay.',
    steps: ['Enter the loan amount, rate and tenure.', 'Try different tenures to compare.', 'Check total interest before you decide.'],
    faqs: [{ q: 'Is the EMI the same every month?', a: 'Yes, for a fixed-rate loan. The interest part falls and the principal part rises each month.' }],
    related: ['home-loan-emi-calculator'],
    keywords: ['car loan emi calculator', 'vehicle loan emi', 'auto loan calculator'],
  },
  {
    slug: 'fd-calculator',
    lang: 'en',
    toolId: 'interest-calculator',
    preset: { amount: 100000, rate: 7, years: 5, compounding: 4, monthly: 0 },
    title: 'FD Calculator — Fixed Deposit Maturity Value',
    h1: 'Fixed deposit (FD) calculator',
    description: 'Calculate FD maturity value and interest with quarterly compounding, as used by most Indian banks. Year-by-year table included. Free.',
    intro: 'Enter the deposit, rate and period. Compounding is set to quarterly, the usual method for bank FDs in India, so the result matches bank calculations closely (before TDS).',
    steps: ['Enter the deposit amount, rate and years.', 'Keep quarterly compounding for bank FDs.', 'Read the maturity value and interest.'],
    faqs: [{ q: 'Is tax deducted?', a: 'No. FD interest may be taxable and banks may deduct TDS; this calculator shows the amount before tax.' }],
    related: ['rd-calculator', 'home-loan-emi-calculator'],
    keywords: ['fd calculator', 'fixed deposit calculator', 'fd maturity calculator', 'fd interest calculator'],
  },
  {
    slug: 'rd-calculator',
    lang: 'en',
    toolId: 'interest-calculator',
    preset: { amount: 0, rate: 6.5, years: 3, compounding: 4, monthly: 5000 },
    title: 'RD Calculator — Recurring Deposit Maturity',
    h1: 'Recurring deposit (RD) calculator',
    description: 'Calculate the maturity value of a recurring deposit from your monthly instalment, rate and period. Free, with a yearly table.',
    intro: 'Set the monthly deposit, rate and number of years to see what your RD will be worth, with quarterly compounding as used by Indian banks.',
    steps: ['Enter the monthly deposit, rate and years.', 'Read the maturity value.', 'Compare periods or amounts.'],
    faqs: [{ q: 'When are deposits assumed to be made?', a: 'At the end of each month. Banks that credit at the start of the month will show slightly more.' }],
    related: ['fd-calculator'],
    keywords: ['rd calculator', 'recurring deposit calculator', 'rd maturity calculator'],
  },

  /* ---------- PDF size ---------- */
  ...([
    [100, '100 KB', 'very strict portals'],
    [200, '200 KB', 'most exam and government portals'],
    [1000, '1 MB', 'email attachments and job portals'],
  ] as const).map(
    ([kb, label, who]) =>
      ({
        slug: `compress-pdf-to-${kb >= 1000 ? `${kb / 1000}mb` : `${kb}kb`}`,
        lang: 'en',
        toolId: 'pdf-compressor',
        preset: { mode: 'strong', targetKb: kb, dpi: 150 },
        title: `Compress PDF to ${label} Online — Free, No Upload`,
        h1: `Compress a PDF to ${label}`,
        description: `Reduce a PDF to under ${label} for ${who}. Free, no sign-up — your document is compressed in your browser and never uploaded.`,
        intro: `Upload limits like “PDF under ${label}” are common on ${who}. Choose your PDF and it is rebuilt just under ${label}: pages are stored as images at the best resolution and quality that fit, without going so low that text becomes unreadable. Best for scanned documents, certificates and marksheets.`,
        steps: ['Choose your PDF.', `The target is already set to ${label} — press “Compress PDF”.`, 'Check the new size and download it.'],
        faqs: [
          { q: 'Will the text still be readable?', a: 'Yes — resolution never drops below about 50 dpi, and the tool tells you if the target cannot be reached while staying readable. Text does become part of the image, so it can no longer be selected or searched.' },
          { q: 'My PDF is mostly text. What should I do?', a: 'Try “Light” mode first: it keeps text selectable. If that is not small enough, use Strong mode with “Black and white”, which shrinks text documents a lot.' },
          { q: `Is “${label}” counted as 1000 or 1024?`, a: `Targets are counted in thousands of bytes, so the file also fits portals that count 1 KB as 1024 bytes.` },
        ],
        twin: kb === 200 ? 'hi/pdf-ka-size-kam-kare' : undefined,
        related: ['compress-pdf-to-200kb', 'jpg-to-pdf', 'compress-image-to-100kb'].filter((x) => x !== `compress-pdf-to-${kb}kb`),
        keywords: [`compress pdf to ${label.toLowerCase().replace(' ', '')}`, `pdf ${label.toLowerCase().replace(' ', '')}`, `reduce pdf size to ${label.toLowerCase()}`, 'pdf size reducer'],
      }) as Task,
  ),

  /* ---------- Time ---------- */
  {
    slug: 'hours-calculator',
    lang: 'en',
    toolId: 'time-calculator',
    preset: { mode: 'timesheet' },
    title: 'Hours Calculator — Total Hours Worked with Breaks',
    h1: 'Hours worked calculator',
    description: 'Add up hours worked from start and end times, minus breaks, including night shifts. Get decimal hours for payroll and a CSV timesheet. Free.',
    intro: 'Enter each day’s start and end time and the break in minutes. Night shifts that end after midnight are handled automatically, and the total is shown both as hours:minutes and as decimal hours, which payroll and invoices usually need.',
    steps: ['Enter start and end times for each day (9:30, 21:30 or 9:30 pm).', 'Add break minutes.', 'Read the total and download the timesheet if needed.'],
    faqs: [
      { q: 'How do I convert minutes to decimal hours?', a: 'Divide by 60: 45 minutes is 0.75 hours, so 7 h 45 min is 7.75 hours. The calculator shows both.' },
      { q: 'What about a shift from 10 pm to 6 am?', a: 'An end time earlier than the start is treated as the next day, so 22:00 to 06:00 counts as 8 hours.' },
    ],
    related: ['ist-to-est'],
    keywords: ['hours calculator', 'hours worked calculator', 'timesheet calculator', 'work hours calculator', 'decimal hours'],
  },
  ...([
    ['ist-to-est', 'America/New_York', 'EST/EDT (New York)', 'US Eastern time'],
    ['ist-to-pst', 'America/Los_Angeles', 'PST/PDT (California)', 'US Pacific time'],
    ['ist-to-gmt', 'Europe/London', 'GMT/BST (London)', 'UK time'],
  ] as const).map(
    ([slug, zone, label, plain]) =>
      ({
        slug,
        lang: 'en',
        toolId: 'time-zone-converter',
        preset: { from: 'Asia/Kolkata', to: `${zone},UTC` },
        title: `IST to ${label.split(' ')[0]} Converter — India to ${plain}`,
        h1: `Convert IST to ${label}`,
        description: `Convert Indian Standard Time to ${plain} for any date, with daylight saving applied automatically. Plan calls and meetings across time zones. Free.`,
        intro: `India does not change its clocks, but ${plain} does, so the gap changes during the year. Pick a date and time in IST and see the exact ${plain} — and the other way round with one tap.`,
        steps: ['Pick the date and the time in IST.', `Read ${plain} below, with “−1 day” or “+1 day” when the date changes.`, 'Tap the arrows on a row to convert from that zone instead.'],
        faqs: [
          { q: `What is the time difference between IST and ${plain}?`, a: `It depends on the date because of daylight saving in ${plain}. Choose a date and the converter shows the exact offset.` },
          { q: 'Can I add more cities?', a: 'Yes — type any city or time zone (for example Europe/Paris or Asia/Dubai) and add it.' },
        ],
        related: ['ist-to-est', 'ist-to-pst', 'ist-to-gmt', 'hours-calculator'].filter((x) => x !== slug),
        keywords: [`ist to ${slug.slice(7)}`, `india time to ${plain.toLowerCase()}`, 'time zone converter', 'meeting time converter'],
      }) as Task,
  ),

  /* ---------- Presentations ---------- */
  {
    slug: 'extract-images-from-pptx',
    lang: 'en',
    toolId: 'presentation-info',
    title: 'Extract Images from PowerPoint (PPTX) — Free',
    h1: 'Extract all images from a PowerPoint',
    description: 'Save every picture, video and audio file embedded in a .pptx — one at a time or all as a ZIP — plus the slide text and notes. Free and private.',
    intro: 'Open a .pptx and every embedded picture appears as a thumbnail, in its original quality. Save one, or download them all in a ZIP. The slide titles, text and speaker notes are listed too, ready to copy.',
    steps: ['Open the .pptx file.', 'Click a picture to save it, or use “All (ZIP)”.', 'Copy or download the slide text if you need it.'],
    faqs: [
      { q: 'Are the images resized?', a: 'No — they are saved exactly as they are stored inside the presentation.' },
      { q: 'Does it work with .ppt files?', a: 'Only .pptx. Open an old .ppt in PowerPoint, Google Slides or LibreOffice and save it as .pptx first.' },
    ],
    keywords: ['extract images from pptx', 'save images from powerpoint', 'pptx to text', 'download images from presentation'],
  },

  /* ---------- Hindi: PDF size ---------- */
  {
    slug: 'hi/pdf-ka-size-kam-kare',
    lang: 'hi',
    toolId: 'pdf-compressor',
    preset: { mode: 'strong', targetKb: 200, dpi: 150 },
    title: 'PDF का साइज़ कम करें — 200 KB तक, मुफ़्त',
    h1: 'PDF का साइज़ 200 KB से कम करें',
    description: 'परीक्षा और सरकारी पोर्टल के लिए PDF को 200 KB से कम करें। मुफ़्त, बिना साइन-अप — आपकी PDF अपलोड नहीं होती।',
    intro: 'कई पोर्टल 200 KB से बड़ी PDF नहीं लेते। अपनी PDF चुनें — टारगेट पहले से 200 KB है। पेज इमेज के रूप में सबसे अच्छी क्वालिटी पर रखे जाते हैं जो सीमा में आए, और टेक्स्ट पढ़ने लायक बना रहता है। स्कैन किए दस्तावेज़ और मार्कशीट के लिए सबसे अच्छा।',
    steps: ['PDF चुनें।', '“Compress PDF” दबाएँ — टारगेट 200 KB है।', 'नया साइज़ देखें और डाउनलोड करें।'],
    faqs: [
      { q: 'क्या टेक्स्ट पढ़ा जा सकेगा?', a: 'हाँ। रेज़ोल्यूशन लगभग 50 dpi से नीचे नहीं जाता। पर टेक्स्ट इमेज का हिस्सा बन जाता है, इसलिए उसे कॉपी या सर्च नहीं किया जा सकता।' },
      { q: 'साइज़ और कम चाहिए तो?', a: '“Black and white” चालू करें — टेक्स्ट वाले दस्तावेज़ इससे बहुत छोटे हो जाते हैं।' },
    ],
    twin: 'compress-pdf-to-200kb',
    related: ['hi/photo-ka-size-kam-kare', 'hi/jpg-se-pdf'],
    keywords: ['pdf ka size kam kare', 'पीडीएफ का साइज़ कम करें', 'pdf 200kb', 'pdf size kam kaise kare'],
  },

  /* ---------- Hindi ---------- */
  {
    slug: 'hi/photo-ka-size-kam-kare',
    lang: 'hi',
    toolId: 'image-compressor',
    preset: { targetKb: 50, format: 'image/jpeg' },
    title: 'फोटो का साइज़ KB में कम करें — मुफ़्त, बिना अपलोड',
    h1: 'फोटो का साइज़ KB में कम करें',
    description: 'ऑनलाइन फ़ॉर्म, ईमेल या व्हाट्सऐप के लिए फोटो का साइज़ 20, 50 या 100 KB तक कम करें। आपकी फोटो आपके डिवाइस से बाहर नहीं जाती।',
    intro: 'जितने KB चाहिए वह लिखें या कोई प्रीसेट चुनें। फोटो उससे थोड़ा छोटा हो जाएगा — क्वालिटी सिर्फ़ ज़रूरत भर कम की जाती है, और ज़रूरत पड़ने पर ही फोटो की लंबाई-चौड़ाई घटाई जाती है। कई फोटो एक साथ हो सकते हैं।',
    steps: ['एक या ज़्यादा फोटो चुनें।', 'KB में साइज़ लिखें (पहले से 50 KB सेट है)।', '“Process” दबाएँ और फोटो डाउनलोड करें।'],
    faqs: [
      { q: 'क्या मेरी फोटो अपलोड होती है?', a: 'नहीं। सारा काम आपके ब्राउज़र में होता है, इसलिए निजी दस्तावेज़ों के लिए भी सुरक्षित है।' },
      { q: 'फोटो धुंधली लगे तो क्या करें?', a: 'पहले फोटो को क्रॉप करके फालतू हिस्सा हटाएँ, फिर साइज़ कम करें।' },
    ],
    twin: 'reduce-photo-size-in-kb',
    related: ['hi/photo-20kb-kaise-kare', 'hi/signature-ka-size-kam-kare', 'hi/jpg-se-pdf'],
    keywords: ['फोटो का साइज़ कम करें', 'photo ka size kam kare', 'फोटो kb कम करें', 'image size kam kaise kare'],
  },
  {
    slug: 'hi/photo-20kb-kaise-kare',
    lang: 'hi',
    toolId: 'image-compressor',
    preset: { targetKb: 20, format: 'image/jpeg' },
    title: 'फोटो 20 KB में कैसे करें — ऑनलाइन फ़ॉर्म के लिए',
    h1: 'फोटो को 20 KB से कम करें',
    description: 'परीक्षा और सरकारी फ़ॉर्म के लिए फोटो या JPG को 20 KB से कम करें। मुफ़्त, बिना साइन-अप और बिना अपलोड।',
    intro: 'कई पोर्टल 20 KB से बड़ी फोटो स्वीकार नहीं करते। फोटो चुनें — टारगेट पहले से 20 KB है। नतीजा 20,000 बाइट से कम होगा, इसलिए वे पोर्टल भी स्वीकार करेंगे जो 1 KB को 1024 बाइट गिनते हैं।',
    steps: ['फोटो चुनें (JPG, PNG या WebP)।', '“Process” दबाएँ।', 'नया साइज़ देखें और डाउनलोड करें।'],
    faqs: [{ q: 'फ़ॉर्म पिक्सल साइज़ भी माँगे तो?', a: 'पहले “Resize Image” टूल से पिक्सल साइज़ सेट करें, फिर यहाँ 20 KB से कम करें।' }],
    twin: 'compress-image-to-20kb',
    related: ['hi/photo-ka-size-kam-kare', 'hi/signature-ka-size-kam-kare'],
    keywords: ['फोटो 20kb', 'photo 20kb kaise kare', '20 kb photo', 'फोटो का साइज़ 20kb'],
  },
  {
    slug: 'hi/signature-ka-size-kam-kare',
    lang: 'hi',
    toolId: 'image-compressor',
    preset: { targetKb: 20, format: 'image/jpeg' },
    title: 'सिग्नेचर का साइज़ कम करें — 10 से 20 KB',
    h1: 'सिग्नेचर का साइज़ ऑनलाइन फ़ॉर्म के लिए कम करें',
    description: 'स्कैन या फोटो किए गए हस्ताक्षर को परीक्षा, बैंक और सरकारी फ़ॉर्म के लिए 10–20 KB के JPG में बदलें। मुफ़्त और सुरक्षित।',
    intro: 'सफ़ेद कागज़ पर काले या नीले पेन से हस्ताक्षर करें, फोटो लें, हस्ताक्षर के चारों ओर क्रॉप करें और यहाँ साइज़ कम करें। टारगेट 20 KB है; फ़ॉर्म कम माँगे तो 10 लिखें।',
    steps: ['फोटो को सिर्फ़ हस्ताक्षर तक क्रॉप करें।', 'यहाँ फोटो डालें — टारगेट 20 KB है।', '“Process” दबाएँ और JPG डाउनलोड करें।'],
    faqs: [{ q: '20 KB से कम होने पर भी फ़ॉर्म क्यों नहीं ले रहा?', a: 'कई फ़ॉर्म पिक्सल साइज़ या न्यूनतम साइज़ (जैसे 10 KB) भी जाँचते हैं। उन शर्तों को भी पूरा करें।' }],
    twin: 'compress-signature-for-online-form',
    related: ['hi/photo-20kb-kaise-kare', 'hi/photo-ka-size-kam-kare'],
    keywords: ['सिग्नेचर का साइज़ कम करें', 'signature ka size kam kare', 'signature 20kb'],
  },
  {
    slug: 'hi/jpg-se-pdf',
    lang: 'hi',
    toolId: 'image-to-pdf',
    title: 'JPG से PDF बनाएँ — मुफ़्त, बिना वॉटरमार्क',
    h1: 'JPG फोटो से PDF बनाएँ',
    description: 'एक या कई JPG फोटो को एक PDF में बदलें। पेज का क्रम बदलें, पेज साइज़ चुनें। मुफ़्त, बिना वॉटरमार्क, फ़ाइल अपलोड नहीं होती।',
    intro: 'मार्कशीट, रसीद या दस्तावेज़ों की फोटो जोड़ें, क्रम ठीक करें और एक PDF बनाएँ। हर फोटो एक पेज बनती है।',
    steps: ['JPG फोटो चुनें (कई एक साथ)।', 'क्रम और पेज साइज़ चुनें।', 'PDF बनाएँ और डाउनलोड करें।'],
    faqs: [{ q: 'क्या PDF पर वॉटरमार्क आता है?', a: 'नहीं, कोई वॉटरमार्क या पेज-सीमा नहीं है।' }],
    twin: 'jpg-to-pdf',
    related: ['hi/pdf-se-jpg', 'hi/photo-ka-size-kam-kare'],
    keywords: ['jpg se pdf', 'jpg से pdf', 'photo se pdf kaise banaye', 'फोटो से पीडीएफ'],
  },
  {
    slug: 'hi/pdf-se-jpg',
    lang: 'hi',
    toolId: 'pdf-to-image',
    preset: { format: 'image/jpeg' },
    title: 'PDF से JPG बनाएँ — हर पेज की फोटो',
    h1: 'PDF को JPG फोटो में बदलें',
    description: 'PDF के हर पेज को JPG फोटो में बदलें — 72, 150 या 300 dpi। मुफ़्त, आपकी PDF आपके डिवाइस पर ही रहती है।',
    intro: 'PDF चुनें, पेज और क्वालिटी चुनें और फोटो डाउनलोड करें। व्हाट्सऐप के लिए 150 dpi और प्रिंट के लिए 300 dpi अच्छा है।',
    steps: ['PDF चुनें।', 'JPG पहले से चुना है — dpi और पेज चुनें।', 'बदलें और डाउनलोड करें।'],
    faqs: [{ q: 'क्या सिर्फ़ एक पेज बदल सकते हैं?', a: 'हाँ, बदलने से पहले सिर्फ़ ज़रूरी पेज चुनें।' }],
    twin: 'pdf-to-jpg',
    related: ['hi/jpg-se-pdf'],
    keywords: ['pdf se jpg', 'pdf से jpg', 'pdf ko photo me kaise badle'],
  },
  {
    slug: 'hi/upi-qr-code-banaye',
    lang: 'hi',
    toolId: 'qr-generator',
    preset: { kind: 'upi' },
    title: 'UPI QR कोड बनाएँ — दुकान के लिए मुफ़्त',
    h1: 'अपनी दुकान का UPI QR कोड बनाएँ',
    description: 'Google Pay, PhonePe, Paytm और BHIM के लिए UPI QR कोड बनाएँ, चाहें तो तय रकम के साथ। अपना लोगो और रंग जोड़ें। मुफ़्त।',
    intro: 'अपना UPI ID (जैसे shopname@okaxis) और नाम लिखें, चाहें तो रकम और नोट जोड़ें, और कोड प्रिंट करके काउंटर पर लगाएँ। कोई भी UPI ऐप इसे स्कैन कर सकता है।',
    steps: ['UPI ID और नाम लिखें।', 'चाहें तो रकम, लोगो और कैप्शन जोड़ें।', 'अपने फ़ोन से एक बार स्कैन करके जाँचें, फिर प्रिंट करें।'],
    faqs: [{ q: 'क्या यह सुरक्षित है?', a: 'कोड में सिर्फ़ आपका UPI ID और नाम होता है — कोई PIN या बैंक जानकारी नहीं। पैसे भेजने वाले को भुगतान से पहले आपका नाम दिखता है।' }],
    twin: 'upi-qr-code-generator',
    related: ['hi/jpg-se-pdf'],
    keywords: ['upi qr code kaise banaye', 'upi qr code banaye', 'दुकान का qr code', 'phonepe qr code kaise banaye'],
  },
  {
    slug: 'hi/umar-calculator',
    lang: 'hi',
    toolId: 'date-calculator',
    preset: { mode: 'age' },
    title: 'उम्र कैलकुलेटर — साल, महीने और दिन में सही उम्र',
    h1: 'उम्र कैलकुलेटर (Age Calculator)',
    description: 'जन्मतिथि से किसी भी तारीख़ पर सही उम्र साल, महीने और दिन में जानें — परीक्षा की आयु-सीमा जाँचने के लिए उपयोगी। मुफ़्त।',
    intro: 'जन्मतिथि डालें और “Age on” में वह तारीख़ चुनें जिस पर उम्र गिननी है — परीक्षा अधिसूचनाएँ अक्सर किसी तय तारीख़ “को” उम्र माँगती हैं।',
    steps: ['जन्मतिथि डालें।', 'ज़रूरत हो तो “Age on” की तारीख़ बदलें।', 'उम्र, कुल दिन और अगला जन्मदिन देखें।'],
    faqs: [{ q: '29 फ़रवरी को जन्म हो तो?', a: 'सामान्य वर्षों में जन्मदिन 28 फ़रवरी को गिना जाता है।' }],
    twin: 'age-calculator',
    related: ['hi/photo-ka-size-kam-kare'],
    keywords: ['umar calculator', 'उम्र कैलकुलेटर', 'age calculator hindi', 'जन्मतिथि से उम्र'],
  },
];

const bySlug = new Map(TASKS.map((t) => [t.slug, t]));
export const getTask = (slug: string) => bySlug.get(slug);
export const tasksForTool = (toolId: string, lang: Task['lang'] = 'en') => TASKS.filter((t) => t.toolId === toolId && t.lang === lang);
